/**
 * Re-export Myanmar / practice paper maps from @the-ants/shared-types
 * so web and API share one source of truth.
 */
export {
  CAIE_IGCSE_MYANMAR_PAPERS,
  CAIE_IGCSE_PRACTICE_VARIANTS,
  CAIE_ALEVEL_MYANMAR_PAPERS,
  CAIE_ALEVEL_PRACTICE_VARIANTS,
  CAIE_ALEVEL_AWARD_PAPERS,
  CAIE_SERIES_PAPERS,
  CAIE_COUNTDOWN_EXCLUDED,
  EDEXCEL_IGCSE_MYANMAR_PAPERS,
  EDEXCEL_IGCSE_PRACTICE_PAPERS,
  EDEXCEL_IAL_MYANMAR_UNITS,
  boardFromCurriculumCode,
  caiePaperBaseFromNumber,
  examMatchesMyanmarPaper,
  examRowMatchesMyanmar,
  formatPaperRowLabel,
  getMyanmarPaperIds,
  getAllPracticePaperIds,
  getRequiredPaperIds,
  getPracticePaperIds,
  isEndorsementPaper,
  ENDORSEMENT_PAPER_IDS,
  pastPaperMatchesAllPracticeSet,
  paperIdMatchesPracticeSet,
  parseExamSeason,
  pastPaperMatchesMyanmarPaper,
  pastPaperMatchesPracticeSet,
  syllabusHasAwardLevel,
  syllabusNeedsMathsRoute,
  toCambridgePaperId,
  type AwardLevel,
  type ExamBoardFilter,
  type ExamSeason,
  type MathsRoute,
  type MyanmarMatchOptions,
  type PaperPreferences,
} from '@the-ants/shared-types';
