INSERT OR IGNORE INTO subjects (id, curriculum_id, name, code, description, color_code, created_at) VALUES
('subj-caie-igcse-eng-first', 'curr-caie-igcse', 'First Language English', '0500', 'Cambridge IGCSE First Language English', '#ef4444', strftime('%s', 'now') * 1000),
('subj-caie-igcse-esl', 'curr-caie-igcse', 'English as a Second Language', '0510', 'Cambridge IGCSE English as a Second Language (Speaking Endorsement)', '#f97316', strftime('%s', 'now') * 1000),
('subj-caie-igcse-econ', 'curr-caie-igcse', 'Economics', '0455', 'Cambridge IGCSE Economics', '#14b8a6', strftime('%s', 'now') * 1000),
('subj-caie-al-bio', 'curr-caie-alevel', 'Biology', '9700', 'Cambridge International AS & A Level Biology', '#10b981', strftime('%s', 'now') * 1000),
('subj-caie-al-cs', 'curr-caie-alevel', 'Computer Science', '9618', 'Cambridge International AS & A Level Computer Science', '#f59e0b', strftime('%s', 'now') * 1000),
('subj-caie-al-econ', 'curr-caie-alevel', 'Economics', '9708', 'Cambridge International AS & A Level Economics', '#14b8a6', strftime('%s', 'now') * 1000),
('subj-edx-igcse-fmaths', 'curr-edexcel-igcse', 'Further Pure Mathematics', '4PM1', 'Pearson Edexcel International GCSE Further Pure Mathematics', '#2563eb', strftime('%s', 'now') * 1000),
('subj-edx-igcse-chem', 'curr-edexcel-igcse', 'Chemistry', '4CH1', 'Pearson Edexcel International GCSE Chemistry', '#ec4899', strftime('%s', 'now') * 1000),
('subj-edx-igcse-bio', 'curr-edexcel-igcse', 'Biology', '4BI1', 'Pearson Edexcel International GCSE Biology', '#10b981', strftime('%s', 'now') * 1000),
('subj-edx-igcse-ict', 'curr-edexcel-igcse', 'Information and Communication Technology', '4IT1', 'Pearson Edexcel International GCSE ICT', '#f59e0b', strftime('%s', 'now') * 1000),
('subj-edx-igcse-biz', 'curr-edexcel-igcse', 'Business', '4BS1', 'Pearson Edexcel International GCSE Business', '#6366f1', strftime('%s', 'now') * 1000),
('subj-edx-igcse-econ', 'curr-edexcel-igcse', 'Economics', '4EC1', 'Pearson Edexcel International GCSE Economics', '#14b8a6', strftime('%s', 'now') * 1000),
('subj-edx-igcse-acc', 'curr-edexcel-igcse', 'Accounting', '4AC1', 'Pearson Edexcel International GCSE Accounting', '#eab308', strftime('%s', 'now') * 1000),
('subj-edx-igcse-eng-a', 'curr-edexcel-igcse', 'English Language A', '4EA1', 'Pearson Edexcel International GCSE English Language A', '#ef4444', strftime('%s', 'now') * 1000),
('subj-edx-ial-pure4', 'curr-edexcel-ial', 'Pure Mathematics 4', 'WMA14', 'Pearson Edexcel IAL Pure Mathematics Unit 4', '#1e3a8a', strftime('%s', 'now') * 1000),
('subj-edx-ial-mech1', 'curr-edexcel-ial', 'Mechanics M1', 'WME01', 'Pearson Edexcel IAL Mechanics Unit 1', '#7c3aed', strftime('%s', 'now') * 1000),
('subj-edx-ial-mech2', 'curr-edexcel-ial', 'Mechanics M2', 'WME02', 'Pearson Edexcel IAL Mechanics Unit 2', '#6d28d9', strftime('%s', 'now') * 1000),
('subj-edx-ial-stat1', 'curr-edexcel-ial', 'Statistics S1', 'WST01', 'Pearson Edexcel IAL Statistics Unit 1', '#0ea5e9', strftime('%s', 'now') * 1000),
('subj-edx-ial-stat2', 'curr-edexcel-ial', 'Statistics S2', 'WST02', 'Pearson Edexcel IAL Statistics Unit 2', '#0284c7', strftime('%s', 'now') * 1000),
('subj-edx-ial-phys2', 'curr-edexcel-ial', 'Physics Unit 2', 'WPH12', 'Pearson Edexcel IAL Waves and Electricity', '#7c3aed', strftime('%s', 'now') * 1000),
('subj-edx-ial-phys3', 'curr-edexcel-ial', 'Physics Unit 3', 'WPH13', 'Pearson Edexcel IAL Practical Skills in Physics I', '#6d28d9', strftime('%s', 'now') * 1000),
('subj-edx-ial-phys4', 'curr-edexcel-ial', 'Physics Unit 4', 'WPH14', 'Pearson Edexcel IAL Further Mechanics, Fields and Particles', '#5b21b6', strftime('%s', 'now') * 1000),
('subj-edx-ial-phys5', 'curr-edexcel-ial', 'Physics Unit 5', 'WPH15', 'Pearson Edexcel IAL Thermodynamics, Radiation and Oscillations', '#4c1d95', strftime('%s', 'now') * 1000),
('subj-edx-ial-phys6', 'curr-edexcel-ial', 'Physics Unit 6', 'WPH16', 'Pearson Edexcel IAL Practical Skills in Physics II', '#3730a3', strftime('%s', 'now') * 1000),
('subj-edx-ial-chem1', 'curr-edexcel-ial', 'Chemistry Unit 1', 'WCH11', 'Pearson Edexcel IAL Structure, Bonding and Introduction to Organic Chemistry', '#db2777', strftime('%s', 'now') * 1000),
('subj-edx-ial-chem2', 'curr-edexcel-ial', 'Chemistry Unit 2', 'WCH12', 'Pearson Edexcel IAL Energetics, Group Chemistry and Halogenoalkanes', '#be185d', strftime('%s', 'now') * 1000),
('subj-edx-ial-chem3', 'curr-edexcel-ial', 'Chemistry Unit 3', 'WCH13', 'Pearson Edexcel IAL Practical Skills in Chemistry I', '#9d174d', strftime('%s', 'now') * 1000),
('subj-edx-ial-chem4', 'curr-edexcel-ial', 'Chemistry Unit 4', 'WCH14', 'Pearson Edexcel IAL Rates, Equilibria and Further Organic Chemistry', '#831843', strftime('%s', 'now') * 1000),
('subj-edx-ial-chem5', 'curr-edexcel-ial', 'Chemistry Unit 5', 'WCH15', 'Pearson Edexcel IAL Transition Metals and Organic Nitrogen Chemistry', '#701a75', strftime('%s', 'now') * 1000),
('subj-edx-ial-chem6', 'curr-edexcel-ial', 'Chemistry Unit 6', 'WCH16', 'Pearson Edexcel IAL Practical Skills in Chemistry II', '#581c87', strftime('%s', 'now') * 1000),
('subj-edx-ial-bio1', 'curr-edexcel-ial', 'Biology Unit 1', 'WBI11', 'Pearson Edexcel IAL Molecules, Diet, Transport and Health', '#059669', strftime('%s', 'now') * 1000),
('subj-edx-ial-bio2', 'curr-edexcel-ial', 'Biology Unit 2', 'WBI12', 'Pearson Edexcel IAL Cells, Development, Biodiversity and Conservation', '#047857', strftime('%s', 'now') * 1000),
('subj-edx-ial-bio3', 'curr-edexcel-ial', 'Biology Unit 3', 'WBI13', 'Pearson Edexcel IAL Practical Skills in Biology I', '#065f46', strftime('%s', 'now') * 1000),
('subj-edx-ial-bio4', 'curr-edexcel-ial', 'Biology Unit 4', 'WBI14', 'Pearson Edexcel IAL Energy, Environment, Microbiology and Immunity', '#064e3b', strftime('%s', 'now') * 1000),
('subj-edx-ial-bio5', 'curr-edexcel-ial', 'Biology Unit 5', 'WBI15', 'Pearson Edexcel IAL Respiration, Internal Environment, Coordination and Gene Technology', '#022c22', strftime('%s', 'now') * 1000),
('subj-edx-ial-bio6', 'curr-edexcel-ial', 'Biology Unit 6', 'WBI16', 'Pearson Edexcel IAL Practical Skills in Biology II', '#14532d', strftime('%s', 'now') * 1000),
('subj-edx-ial-econ1', 'curr-edexcel-ial', 'Economics Unit 1', 'WEC11', 'Pearson Edexcel IAL Markets in Action', '#0d9488', strftime('%s', 'now') * 1000),
('subj-edx-ial-econ2', 'curr-edexcel-ial', 'Economics Unit 2', 'WEC12', 'Pearson Edexcel IAL Macroeconomic Performance and Policy', '#0f766e', strftime('%s', 'now') * 1000),
('subj-edx-ial-econ3', 'curr-edexcel-ial', 'Economics Unit 3', 'WEC13', 'Pearson Edexcel IAL Business Behaviour', '#115e59', strftime('%s', 'now') * 1000),
('subj-edx-ial-econ4', 'curr-edexcel-ial', 'Economics Unit 4', 'WEC14', 'Pearson Edexcel IAL Developments in the Global Economy', '#134e4a', strftime('%s', 'now') * 1000),
('subj-edx-ial-biz1', 'curr-edexcel-ial', 'Business Unit 1', 'WBS11', 'Pearson Edexcel IAL Marketing and People', '#4f46e5', strftime('%s', 'now') * 1000),
('subj-edx-ial-biz2', 'curr-edexcel-ial', 'Business Unit 2', 'WBS12', 'Pearson Edexcel IAL Managing Business Activities', '#4338ca', strftime('%s', 'now') * 1000),
('subj-edx-ial-biz3', 'curr-edexcel-ial', 'Business Unit 3', 'WBS13', 'Pearson Edexcel IAL Business Decisions and Strategy', '#3730a3', strftime('%s', 'now') * 1000),
('subj-edx-ial-biz4', 'curr-edexcel-ial', 'Business Unit 4', 'WBS14', 'Pearson Edexcel IAL Global Business', '#312e81', strftime('%s', 'now') * 1000),
('subj-edx-ial-acc1', 'curr-edexcel-ial', 'Accounting Unit 1', 'WAC11', 'Pearson Edexcel IAL The Accounting System and Costing', '#ca8a04', strftime('%s', 'now') * 1000),
('subj-edx-ial-acc2', 'curr-edexcel-ial', 'Accounting Unit 2', 'WAC12', 'Pearson Edexcel IAL Corporate and Management Accounting', '#a16207', strftime('%s', 'now') * 1000);
