-- 0018_backfill_edexcel_igcse_subtopics.sql
-- Backfill subtopics for Edexcel IGCSE topics from official specification PDFs

UPDATE topics SET subtopics='[{"code": "1.1", "title": "Integers"}, {"code": "1.2", "title": "Fractions"}, {"code": "1.3", "title": "Decimals"}, {"code": "1.4", "title": "Powers and"}, {"code": "1.5", "title": "Set language"}, {"code": "1.6", "title": "Percentages"}, {"code": "1.7", "title": "Ratio and"}, {"code": "1.8", "title": "Degree of"}, {"code": "1.9", "title": "Standard"}, {"code": "1.10", "title": "Applying"}, {"code": "1.11", "title": "Electronic"}, {"code": "1.9", "title": "Standard form"}]', subtopics_count=12, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-maths-a-01';
UPDATE topics SET subtopics='[{"code": "2.1", "title": "Use of"}, {"code": "2.2", "title": "Algebraic"}, {"code": "2.3", "title": "Expressions"}, {"code": "2.1", "title": "Use of symbols"}, {"code": "2.3", "title": "Expressions and"}]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-maths-a-02';
UPDATE topics SET subtopics='[{"code": "3.1", "title": "Sequences"}, {"code": "3.2", "title": "Function"}, {"code": "3.3", "title": "Graphs"}, {"code": "3.4", "title": "Calculus"}]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-maths-a-03';
UPDATE topics SET subtopics='[{"code": "4.1", "title": "Angles, lines"}, {"code": "4.2", "title": "Polygons"}, {"code": "4.3", "title": "Symmetry"}, {"code": "4.4", "title": "Measures"}, {"code": "4.5", "title": "Construction"}, {"code": "4.6", "title": "Circle properties"}, {"code": "4.7", "title": "Geometrical"}, {"code": "4.8", "title": "Trigonometry"}, {"code": "4.9", "title": "Mensuration"}, {"code": "4.11", "title": "Similarity"}]', subtopics_count=10, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-maths-a-04';
UPDATE topics SET subtopics='[{"code": "5.1", "title": "Vectors"}, {"code": "5.2", "title": "Transformation"}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-maths-a-05';
UPDATE topics SET subtopics='[{"code": "6.1", "title": "Graphical"}, {"code": "6.2", "title": "Statistical"}, {"code": "6.3", "title": "Probability"}]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-maths-a-06';
UPDATE topics SET subtopics='[{"code": "2.20", "title": "know that:"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-02';
UPDATE topics SET subtopics='[{"code": "3.2", "title": "explain the difference between longitudinal and transverse waves"}, {"code": "3.6", "title": "use the relationship between frequency and time period:"}, {"code": "3.16", "title": "draw ray diagrams to illustrate reflection and refraction"}, {"code": "3.21", "title": "explain the meaning of critical angle c"}]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-03';
UPDATE topics SET subtopics='[{"code": "4.2", "title": "describe energy transfers involving energy stores:"}, {"code": "4.3", "title": "use the principle of conservation of energy"}, {"code": "4.7", "title": "explain the role of convection in everyday phenomena"}, {"code": "4.14", "title": "know and use the relationship:"}]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-04';
UPDATE topics SET subtopics='[{"code": "5.7", "title": "know and use the relationship for pressure difference:"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-05';
UPDATE topics SET subtopics='[{"code": "6.4", "title": "understand the term ''magnetic field line''"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-06';
UPDATE topics SET subtopics='[{"code": "7.14", "title": "describe uses of radioactivity in industry and medicine"}, {"code": "7.15", "title": "describe the difference between contamination and irradiation"}, {"code": "7.16", "title": "describe the dangers of ionising radiations, including:"}]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-07';
UPDATE topics SET subtopics='[{"code": "1.3", "title": "plot and explain distance−time graphs"}, {"code": "1.7", "title": "plot and explain velocity−time graphs"}, {"code": "1.13", "title": "understand how vector quantities differ from scalar quantities"}, {"code": "1.14", "title": "understand that force is a vector quantity"}, {"code": "8.2", "title": "know that:"}, {"code": "8.4", "title": "explain that gravitational force:"}]', subtopics_count=6, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-08';
UPDATE topics SET subtopics='[{"code": "1.4", "title": "know what is meant by the terms:"}, {"code": "1.13", "title": "practical: investigate paper chromatography using inks/food colourings"}, {"code": "1.30", "title": "calculate percentage yield"}, {"code": "1.33", "title": "calculate empirical and molecular formulae from experimental data"}, {"code": "1.38", "title": "know the charges of these ions:"}, {"code": "1.41", "title": "understand ionic bonding in terms of electrostatic attractions"}, {"code": "1.45", "title": "understand covalent bonds in terms of electrostatic attractions"}]', subtopics_count=7, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-chem-01';
UPDATE topics SET subtopics='[{"code": "2.18", "title": "know the conditions under which iron rusts"}, {"code": "2.20", "title": "understand the terms:"}, {"code": "2.32", "title": "know that alkalis can neutralise acids"}, {"code": "2.44", "title": "describe tests for these gases:"}, {"code": "2.45", "title": "describe how to carry out a flame test"}, {"code": "2.47", "title": "describe tests for these cations:"}, {"code": "2.48", "title": "describe tests for these anions:"}]', subtopics_count=7, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-chem-02';
UPDATE topics SET subtopics='[{"code": "4.19", "title": "know the general formula for alkanes"}, {"code": "4.20", "title": "explain why alkanes are classified as saturated hydrocarbons"}, {"code": "4.23", "title": "know that alkenes contain the functional group >C=C<"}, {"code": "4.24", "title": "know the general formula for alkenes"}, {"code": "4.25", "title": "explain why alkenes are classified as unsaturated hydrocarbons"}]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-chem-03';
UPDATE topics SET subtopics='[{"code": "1.1", "title": "understand how living organisms share the following characteristics:"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-bio-01';
UPDATE topics SET subtopics='[{"code": "2.35", "title": "know that ATP provides energy for cells"}, {"code": "2.36", "title": "describe the differences between aerobic and anaerobic respiration"}, {"code": "2.83", "title": "understand that plants respond to stimuli"}, {"code": "2.89", "title": "understand the role of neurotransmitters at synapses"}]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-bio-02';
UPDATE topics SET subtopics='[{"code": "3.1", "title": "understand the differences between sexual and asexual reproduction"}, {"code": "3.5", "title": "practical: investigate the conditions needed for seed germination"}, {"code": "3.24", "title": "understand how to interpret family pedigrees"}, {"code": "3.25", "title": "predict probabilities of outcomes from monohybrid crosses"}, {"code": "3.38", "title": "explain Darwin’s theory of evolution by natural selection"}]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-bio-03';
UPDATE topics SET subtopics='[{"code": "4.1", "title": "understand the terms population, community, habitat and ecosystem"}, {"code": "4.14", "title": "understand how human activities contribute to greenhouse gases"}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-bio-04';
UPDATE topics SET subtopics='[{"code": "1.2", "title": "describe the functions of the cell structures:"}, {"code": "1.3", "title": "describe the structure of a DNA molecule as:"}, {"code": "1.8", "title": "describe protein synthesis as:"}, {"code": "1.9", "title": "outline principles of genetic engineering, including:"}]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-01';
UPDATE topics SET subtopics='[{"code": "2.5", "title": "practical: investigate the energy content of food"}, {"code": "2.9", "title": "describe the advantages of using immobilised enzymes in:"}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-02';
UPDATE topics SET subtopics='[{"code": "4.3", "title": "describe the structure of a synovial joint"}, {"code": "4.6", "title": "understand the causes and symptoms of osteoporosis"}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-03';
UPDATE topics SET subtopics='[{"code": "6.7", "title": "understand the role of digestive enzymes including:"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-04';
UPDATE topics SET subtopics='[{"code": "8.7", "title": "understand the term aerobic exercise"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-05';
UPDATE topics SET subtopics='[{"code": "9.12", "title": "understand the problems associated with heart transplants"}, {"code": "9.15", "title": "explain the terms systolic and diastolic blood pressure"}, {"code": "9.16", "title": "describe the causes, prevention and treatment of hypertension"}, {"code": "9.18", "title": "describe how monoclonal antibodies are produced"}, {"code": "10.4", "title": "explain why the composition of urine may vary"}, {"code": "10.9", "title": "describe the advantages and disadvantages of:"}, {"code": "11.6", "title": "explain the role in pregnancy of the:"}, {"code": "12.2", "title": "know that diseases are caused by pathogenic microorganisms"}, {"code": "12.3", "title": "describe the structure and reproduction of viruses"}, {"code": "12.8", "title": "explain the importance of oral rehydration therapy"}]', subtopics_count=10, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-06';
UPDATE topics SET subtopics='[{"code": "5.9", "title": "understand the action of hormones from the pituitary"}, {"code": "5.10", "title": "understand between the nervous and hormonal systems"}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-09';
UPDATE topics SET subtopics='[{"code": "1.1", "title": "Types of digital devices"}, {"code": "1.2", "title": "Features of digital"}, {"code": "1.3", "title": "Software"}, {"code": "1.4", "title": "Types of peripheral"}, {"code": "1.5", "title": "Types of peripheral"}, {"code": "1.6", "title": "Memory"}, {"code": "1.7", "title": "Processors"}, {"code": "1.8", "title": "ICT systems to meet"}]', subtopics_count=8, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-ict-01';
UPDATE topics SET subtopics='[{"code": "2.1", "title": "Types of digital"}, {"code": "2.2", "title": "Factors influencing the"}, {"code": "2.3", "title": "Requirements for"}, {"code": "2.4", "title": "Benefits of using a"}, {"code": "2.5", "title": "Securing data on a"}]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-ict-02';
UPDATE topics SET subtopics='[{"code": "3.1", "title": "Potential risks to data"}, {"code": "3.2", "title": "Impact of the internet on"}, {"code": "3.3", "title": "Online working from"}, {"code": "3.4", "title": "Impact of the internet on"}, {"code": "3.5", "title": "Impact of the internet on"}, {"code": "3.6", "title": "Types of online"}, {"code": "3.7", "title": "Use of online"}, {"code": "3.8", "title": "Implications of the use"}, {"code": "3.9", "title": "Availability of"}]', subtopics_count=9, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-ict-03';
UPDATE topics SET subtopics='[{"code": "4.1", "title": "Types of services"}, {"code": "4.2", "title": "Impact of online services"}, {"code": "4.3", "title": "Online software"}]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-ict-04';
UPDATE topics SET subtopics='[{"code": "5.1", "title": "Software applications"}, {"code": "5.2", "title": "Data and information"}, {"code": "5.3", "title": "Using software"}, {"code": "5.4", "title": "Reviewing outcomes"}]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-ict-05';
UPDATE topics SET subtopics='[{"code": "6.1", "title": "Word processing"}, {"code": "6.2", "title": "Database management"}, {"code": "6.3", "title": "Spreadsheet"}, {"code": "6.4", "title": "Web authoring"}, {"code": "6.5", "title": "Presentation"}, {"code": "6.6", "title": "Graphics"}, {"code": "6.7", "title": "File management"}]', subtopics_count=7, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-ict-06';
