-- 0018_backfill_edexcel_igcse_subtopics.sql
-- Backfill subtopics for Edexcel IGCSE topics from official specification PDFs

UPDATE topics SET subtopics='["1.1 Integers", "1.2 Fractions", "1.3 Decimals", "1.4 Powers and", "1.5 Set language", "1.6 Percentages", "1.7 Ratio and", "1.8 Degree of", "1.9 Standard", "1.10 Applying", "1.11 Electronic", "1.9 Standard form"]', subtopics_count=12, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-maths-a-01';
UPDATE topics SET subtopics='["2.1 Use of", "2.2 Algebraic", "2.3 Expressions", "2.1 Use of symbols", "2.3 Expressions and"]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-maths-a-02';
UPDATE topics SET subtopics='["3.1 Sequences", "3.2 Function", "3.3 Graphs", "3.4 Calculus"]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-maths-a-03';
UPDATE topics SET subtopics='["4.1 Angles, lines", "4.2 Polygons", "4.3 Symmetry", "4.4 Measures", "4.5 Construction", "4.6 Circle properties", "4.7 Geometrical", "4.8 Trigonometry", "4.9 Mensuration", "4.11 Similarity"]', subtopics_count=10, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-maths-a-04';
UPDATE topics SET subtopics='["5.1 Vectors", "5.2 Transformation"]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-maths-a-05';
UPDATE topics SET subtopics='["6.1 Graphical", "6.2 Statistical", "6.3 Probability"]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-maths-a-06';
UPDATE topics SET subtopics='["2.20 know that:"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-02';
UPDATE topics SET subtopics='["3.2 explain the difference between longitudinal and transverse waves", "3.6 use the relationship between frequency and time period:", "3.16 draw ray diagrams to illustrate reflection and refraction", "3.21 explain the meaning of critical angle c"]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-03';
UPDATE topics SET subtopics='["4.2 describe energy transfers involving energy stores:", "4.3 use the principle of conservation of energy", "4.7 explain the role of convection in everyday phenomena", "4.14 know and use the relationship:"]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-04';
UPDATE topics SET subtopics='["5.7 know and use the relationship for pressure difference:"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-05';
UPDATE topics SET subtopics='["6.4 understand the term ''magnetic field line''"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-06';
UPDATE topics SET subtopics='["7.14 describe uses of radioactivity in industry and medicine", "7.15 describe the difference between contamination and irradiation", "7.16 describe the dangers of ionising radiations, including:"]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-07';
UPDATE topics SET subtopics='["1.3 plot and explain distance−time graphs", "1.7 plot and explain velocity−time graphs", "1.13 understand how vector quantities differ from scalar quantities", "1.14 understand that force is a vector quantity", "8.2 know that:", "8.4 explain that gravitational force:"]', subtopics_count=6, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-phys-08';
UPDATE topics SET subtopics='["1.4 know what is meant by the terms:", "1.13 practical: investigate paper chromatography using inks/food colourings", "1.30 calculate percentage yield", "1.33 calculate empirical and molecular formulae from experimental data", "1.38 know the charges of these ions:", "1.41 understand ionic bonding in terms of electrostatic attractions", "1.45 understand covalent bonds in terms of electrostatic attractions"]', subtopics_count=7, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-chem-01';
UPDATE topics SET subtopics='["2.18 know the conditions under which iron rusts", "2.20 understand the terms:", "2.32 know that alkalis can neutralise acids", "2.44 describe tests for these gases:", "2.45 describe how to carry out a flame test", "2.47 describe tests for these cations:", "2.48 describe tests for these anions:"]', subtopics_count=7, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-chem-02';
UPDATE topics SET subtopics='["4.19 know the general formula for alkanes", "4.20 explain why alkanes are classified as saturated hydrocarbons", "4.23 know that alkenes contain the functional group >C=C<", "4.24 know the general formula for alkenes", "4.25 explain why alkenes are classified as unsaturated hydrocarbons"]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-chem-03';
UPDATE topics SET subtopics='["1.1 understand how living organisms share the following characteristics:"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-bio-01';
UPDATE topics SET subtopics='["2.35 know that ATP provides energy for cells", "2.36 describe the differences between aerobic and anaerobic respiration", "2.83 understand that plants respond to stimuli", "2.89 understand the role of neurotransmitters at synapses"]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-bio-02';
UPDATE topics SET subtopics='["3.1 understand the differences between sexual and asexual reproduction", "3.5 practical: investigate the conditions needed for seed germination", "3.24 understand how to interpret family pedigrees", "3.25 predict probabilities of outcomes from monohybrid crosses", "3.38 explain Darwin’s theory of evolution by natural selection"]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-bio-03';
UPDATE topics SET subtopics='["4.1 understand the terms population, community, habitat and ecosystem", "4.14 understand how human activities contribute to greenhouse gases"]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-bio-04';
UPDATE topics SET subtopics='["1.2 describe the functions of the cell structures:", "1.3 describe the structure of a DNA molecule as:", "1.8 describe protein synthesis as:", "1.9 outline principles of genetic engineering, including:"]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-01';
UPDATE topics SET subtopics='["2.5 practical: investigate the energy content of food", "2.9 describe the advantages of using immobilised enzymes in:"]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-02';
UPDATE topics SET subtopics='["4.3 describe the structure of a synovial joint", "4.6 understand the causes and symptoms of osteoporosis"]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-03';
UPDATE topics SET subtopics='["6.7 understand the role of digestive enzymes including:"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-04';
UPDATE topics SET subtopics='["8.7 understand the term aerobic exercise"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-05';
UPDATE topics SET subtopics='["9.12 understand the problems associated with heart transplants", "9.15 explain the terms systolic and diastolic blood pressure", "9.16 describe the causes, prevention and treatment of hypertension", "9.18 describe how monoclonal antibodies are produced", "10.4 explain why the composition of urine may vary", "10.9 describe the advantages and disadvantages of:", "11.6 explain the role in pregnancy of the:", "12.2 know that diseases are caused by pathogenic microorganisms", "12.3 describe the structure and reproduction of viruses", "12.8 explain the importance of oral rehydration therapy"]', subtopics_count=10, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-06';
UPDATE topics SET subtopics='["5.9 understand the action of hormones from the pituitary", "5.10 understand between the nervous and hormonal systems"]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-human-bio-09';
UPDATE topics SET subtopics='["1.1 Types of digital devices", "1.2 Features of digital", "1.3 Software", "1.4 Types of peripheral", "1.5 Types of peripheral", "1.6 Memory", "1.7 Processors", "1.8 ICT systems to meet"]', subtopics_count=8, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-ict-01';
UPDATE topics SET subtopics='["2.1 Types of digital", "2.2 Factors influencing the", "2.3 Requirements for", "2.4 Benefits of using a", "2.5 Securing data on a"]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-ict-02';
UPDATE topics SET subtopics='["3.1 Potential risks to data", "3.2 Impact of the internet on", "3.3 Online working from", "3.4 Impact of the internet on", "3.5 Impact of the internet on", "3.6 Types of online", "3.7 Use of online", "3.8 Implications of the use", "3.9 Availability of"]', subtopics_count=9, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-ict-03';
UPDATE topics SET subtopics='["4.1 Types of services", "4.2 Impact of online services", "4.3 Online software"]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-ict-04';
UPDATE topics SET subtopics='["5.1 Software applications", "5.2 Data and information", "5.3 Using software", "5.4 Reviewing outcomes"]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-ict-05';
UPDATE topics SET subtopics='["6.1 Word processing", "6.2 Database management", "6.3 Spreadsheet", "6.4 Web authoring", "6.5 Presentation", "6.6 Graphics", "6.7 File management"]', subtopics_count=7, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-igcse-ict-06';
