-- 0019_backfill_edexcel_ial_subtopics.sql
-- Backfill subtopics for Edexcel IAL unit topics from official specification PDFs

UPDATE topics SET subtopics='[{"code": "1.1", "title": "Laws of indices for all rational exponents."}, {"code": "1.2", "title": "Use and manipulation of surds. Students should be able to rationalise denominators."}, {"code": "1.3", "title": "Quadratic functions and their graphs."}, {"code": "1.4", "title": "The discriminant of a quadratic function."}, {"code": "1.5", "title": "Completing the square. Solution of quadratic equations."}, {"code": "1.6", "title": "Solve simultaneous equations; analytical solution by substitution."}, {"code": "1.7", "title": "Interpret linear and quadratic inequalities graphically."}, {"code": "1.8", "title": "Represent linear and quadratic inequalities graphically."}, {"code": "1.9", "title": "Solutions of linear and quadratic inequalities."}, {"code": "1.10", "title": "Algebraic manipulation of polynomials, including expanding"}, {"code": "1.11", "title": "Graphs of functions; sketching curves defined by simple equations."}, {"code": "1.12", "title": "Knowledge of the effect of simple transformations on the graph of"}]', subtopics_count=12, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure1-01';
UPDATE topics SET subtopics='[{"code": "2.1", "title": "Equation of a straight line, including the forms"}, {"code": "2.2", "title": "Conditions for two straight lines to be parallel or perpendicular to each"}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure1-02';
UPDATE topics SET subtopics='[{"code": "3.1", "title": "The sine and cosine rules, and the area of a triangle in the form"}, {"code": "3.2", "title": "Radian measure, including use for arc length and area of sector."}, {"code": "3.3", "title": "Sine, cosine and tangent functions. Their graphs, symmetries and"}]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure1-03';
UPDATE topics SET subtopics='[{"code": "4.1", "title": "The derivative of f(x) as the gradient of the tangent to the graph"}, {"code": "4.2", "title": "Differentiation of xn, and related sums, differences and constant"}, {"code": "4.3", "title": "Applications of differentiation to gradients, tangents and normals."}]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure1-04';
UPDATE topics SET subtopics='[{"code": "5.1", "title": "Indefinite integration as the reverse of differentiation."}, {"code": "5.2", "title": "Integration of xn and related sums, differences and constant multiples."}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure1-05';
UPDATE topics SET subtopics='[{"code": "1.1", "title": "Understand and use the structure of mathematical proof, proceeding"}, {"code": "1.2", "title": "Proof by exhaustion Proof by exhaustion. This involves trying all the options. Suppose x and y are"}, {"code": "1.3", "title": "Disproof by counter example. Disproof by counter example – show that the statement"}]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure2-01';
UPDATE topics SET subtopics='[{"code": "3.1", "title": "Coordinate geometry of the circle using the equation of a circle in the"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure2-02';
UPDATE topics SET subtopics='[{"code": "4.1", "title": "Sequences, including those given by a formula for the nth term and"}, {"code": "4.2", "title": "Understand and work with arithmetic sequences and series,"}, {"code": "4.3", "title": "Increasing sequences, decreasing sequences and periodic sequences."}, {"code": "4.4", "title": "Understand and work with geometric sequences and series,"}, {"code": "4.5", "title": "Binomial expansion of (a + bx)n for positive integer n."}]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure2-03';
UPDATE topics SET subtopics='[{"code": "6.1", "title": "Knowledge and use of tan θ = sin and sin2 θ + cos2 θ = 1."}, {"code": "6.2", "title": "Solution of simple trigonometric equations in a given interval."}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure2-04';
UPDATE topics SET subtopics='[{"code": "5.1", "title": "y = ax and its graph. a > 0, a ≠ 1"}, {"code": "5.2", "title": "Laws of logarithms. To include loga (xy) ≡ loga x + log ay,"}, {"code": "5.3", "title": "The solution of equations of the form ax = b."}]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure2-05';
UPDATE topics SET subtopics='[{"code": "7.1", "title": "Applications of differentiation to maxima and minima and stationary"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure2-06';
UPDATE topics SET subtopics='[{"code": "1.1", "title": "Simplification of rational expressions including factorising"}, {"code": "1.2", "title": "Definition of a function. Domain and range of functions."}, {"code": "1.3", "title": "The modulus function. Students should be able to sketch the graphs of"}, {"code": "1.4", "title": "Combinations of the transformations y = f(x) as represented by y = af(x),"}]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure3-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure3-02';
UPDATE topics SET subtopics='[{"code": "4.1", "title": "Differentiation of ekx, ln kx, sin kx, cos kx, tan kx and their sums and"}, {"code": "4.2", "title": "Differentiation using the product rule, the quotient rule and the chain"}, {"code": "4.3", "title": "The use of For example, finding d x for x = sin 3y"}, {"code": "4.4", "title": "Understand and use exponential growth and decay."}]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure3-03';
UPDATE topics SET subtopics='[{"code": "5.1", "title": "Integration of ekx, 1 nx , sin kx, cos kx"}, {"code": "5.2", "title": "Integration by recognition of known derivatives to include"}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure3-04';
UPDATE topics SET subtopics='[{"code": "6.1", "title": "Location of roots of f(x) = 0 by considering changes of sign of f(x)"}, {"code": "6.2", "title": "Approximate solution of equations using simple iterative methods,"}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure3-05';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure4-01';
UPDATE topics SET subtopics='[{"code": "2.1", "title": "Decompose rational functions into partial fractions (denominators not"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure4-02';
UPDATE topics SET subtopics='[{"code": "3.1", "title": "Parametric equations of curves and conversion between cartesian and"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure4-03';
UPDATE topics SET subtopics='[{"code": "5.1", "title": "Differentiation of simple functions defined implicitly or"}, {"code": "5.2", "title": "Formation of simple differential equations."}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure4-04';
UPDATE topics SET subtopics='[{"code": "5.1", "title": "Differentiation of simple functions defined implicitly or"}, {"code": "5.2", "title": "Formation of simple differential equations."}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure4-05';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure4-06';
UPDATE topics SET subtopics='[{"code": "1.1", "title": "Definition of complex numbers in the form a + ib and"}, {"code": "1.2", "title": "Sum, product and quotient of complex numbers."}, {"code": "1.3", "title": "Geometrical representation of complex numbers in the Argand"}, {"code": "1.4", "title": "Complex solutions of quadratic equations with real coefficients."}, {"code": "1.5", "title": "Finding conjugate complex roots and a real root of a cubic equation"}, {"code": "1.6", "title": "Finding conjugate complex roots and/or real roots of a quartic"}]', subtopics_count=6, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-01';
UPDATE topics SET subtopics='[{"code": "2.1", "title": "Sum of roots and product of roots of a quadratic equation."}, {"code": "2.2", "title": "Manipulation of expressions involving the sum of roots and"}, {"code": "2.3", "title": "Forming quadratic equations with new roots."}]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-02';
UPDATE topics SET subtopics='[{"code": "3.1", "title": "Equations of the form f(x) = 0 solved numerically by:"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-03';
UPDATE topics SET subtopics='[{"code": "4.1", "title": "Cartesian equations for the parabola and rectangular hyperbola."}, {"code": "4.2", "title": "Idea of parametric equation for parabola and rectangular hyperbola."}, {"code": "4.3", "title": "The focus-directrix property of the parabola."}, {"code": "4.4", "title": "Tangents and normals to these curves. Differentiation of y ="}]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-04';
UPDATE topics SET subtopics='[{"code": "5.1", "title": "Addition and subtraction of matrices."}, {"code": "5.2", "title": "Multiplication of a matrix by a scalar."}, {"code": "5.3", "title": "Products of matrices."}, {"code": "5.4", "title": "Evaluation of 2 × 2 determinants. Singular and non-singular matrices."}, {"code": "5.5", "title": "Inverse of 2 × 2 matrices. Use of the relation (AB)–1 = B–1A–1."}]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-05';
UPDATE topics SET subtopics='[{"code": "7.1", "title": "Summation of simple finite series. Students should be able to sum series such as"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-06';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-07';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath2-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath2-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath2-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath2-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath2-05';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath2-06';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath3-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath3-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath3-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath3-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath3-05';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech1-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech1-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech1-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech1-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech1-05';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech2-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech2-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech2-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech2-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech2-05';
UPDATE topics SET subtopics='[{"code": "1.1", "title": "Kinematics of a particle moving in a straight line when the acceleration"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech3-01';
UPDATE topics SET subtopics='[{"code": "2.1", "title": "Elastic strings and springs. Hooke’s law."}, {"code": "2.2", "title": "Energy stored in an elastic string or spring."}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech3-02';
UPDATE topics SET subtopics='[{"code": "3.1", "title": "Newton’s laws of motion, for a particle moving in one dimension,"}, {"code": "3.2", "title": "Simple harmonic motion. Proof that a particle moves with simple harmonic motion in"}, {"code": "3.3", "title": "Oscillations of a particle attached to the end of an elastic string or"}]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech3-03';
UPDATE topics SET subtopics='[{"code": "4.1", "title": "Angular speed."}, {"code": "4.2", "title": "Radial acceleration in circular motion. The forms rω 2 and"}, {"code": "4.3", "title": "Uniform motion of a particle moving in a horizontal circle."}, {"code": "4.4", "title": "Motion of a particle in a vertical circle."}]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech3-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech3-05';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat1-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat1-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat1-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat1-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat1-05';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat2-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat2-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat2-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat2-04';
UPDATE topics SET subtopics='[{"code": "1.1", "title": "Distribution of linear combinations of independent Normal random"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat3-01';
UPDATE topics SET subtopics='[{"code": "2.1", "title": "Methods for collecting data. Simple random sampling. Use of random"}, {"code": "2.2", "title": "Other methods of sampling: stratified, systematic, quota."}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat3-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat3-03';
UPDATE topics SET subtopics='[{"code": "4.1", "title": "The null and alternative hypotheses. The use of"}, {"code": "4.2", "title": "Degrees of freedom. Students will be expected to determine the degrees of"}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat3-04';
UPDATE topics SET subtopics='[{"code": "5.1", "title": "Spearman’s rank correlation coefficient, its use, interpretation"}, {"code": "5.2", "title": "Testing the hypothesis that a correlation is zero."}]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat3-05';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-dec1-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-dec1-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-dec1-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-dec1-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-dec1-05';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-dec1-06';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys1-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys1-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys2-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys2-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys3-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys4-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys4-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys4-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys5-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys5-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys5-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys5-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-phys6-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem1-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem1-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem1-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem1-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem1-05';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem2-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem2-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem2-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem2-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem2-05';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem3-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem4-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem4-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem4-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem4-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem4-05';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem5-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem5-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem5-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem5-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-chem6-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio1-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio1-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio1-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio2-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio2-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio2-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio3-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio4-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio4-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio4-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio4-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio5-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio5-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio5-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio5-04';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-bio6-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-biz1-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-biz1-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-biz2-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-biz2-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-biz3-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-biz3-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-biz4-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-biz4-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-econ1-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-econ1-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-econ2-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-econ2-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-econ3-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-econ3-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-econ4-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-econ4-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-acc1-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-acc1-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-acc1-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-acc2-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-acc2-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-acc2-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-it1-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-it1-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-it1-03';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-it2-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-it2-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-it3-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-it3-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-it4-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-it4-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-cs1-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-cs1-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-cs2-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-cs2-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-cs3-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-cs3-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-cs4-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-cs4-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-psych1-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-psych1-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-psych2-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-psych2-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-psych3-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-psych3-02';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-psych4-01';
UPDATE topics SET subtopics='[{"code": "", "title": "Coming soon"}]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-psych4-02';
