-- 0019_backfill_edexcel_ial_subtopics.sql
-- Backfill subtopics for Edexcel IAL unit topics from official specification PDFs

UPDATE topics SET subtopics='["1.1 Laws of indices for all rational exponents.", "1.2 Use and manipulation of surds. Students should be able to rationalise denominators.", "1.3 Quadratic functions and their graphs.", "1.4 The discriminant of a quadratic function.", "1.5 Completing the square. Solution of quadratic equations.", "1.6 Solve simultaneous equations; analytical solution by substitution.", "1.7 Interpret linear and quadratic inequalities graphically.", "1.8 Represent linear and quadratic inequalities graphically.", "1.9 Solutions of linear and quadratic inequalities.", "1.10 Algebraic manipulation of polynomials, including expanding", "1.11 Graphs of functions; sketching curves defined by simple equations.", "1.12 Knowledge of the effect of simple transformations on the graph of"]', subtopics_count=12, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure1-01';
UPDATE topics SET subtopics='["2.1 Equation of a straight line, including the forms", "2.2 Conditions for two straight lines to be parallel or perpendicular to each"]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure1-02';
UPDATE topics SET subtopics='["3.1 The sine and cosine rules, and the area of a triangle in the form", "3.2 Radian measure, including use for arc length and area of sector.", "3.3 Sine, cosine and tangent functions. Their graphs, symmetries and"]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure1-03';
UPDATE topics SET subtopics='["4.1 The derivative of f(x) as the gradient of the tangent to the graph", "4.2 Differentiation of xn, and related sums, differences and constant", "4.3 Applications of differentiation to gradients, tangents and normals."]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure1-04';
UPDATE topics SET subtopics='["5.1 Indefinite integration as the reverse of differentiation.", "5.2 Integration of xn and related sums, differences and constant multiples."]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure1-05';
UPDATE topics SET subtopics='["1.1 Understand and use the structure of mathematical proof, proceeding", "1.2 Proof by exhaustion Proof by exhaustion. This involves trying all the options. Suppose x and y are", "1.3 Disproof by counter example. Disproof by counter example – show that the statement"]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure2-01';
UPDATE topics SET subtopics='["3.1 Coordinate geometry of the circle using the equation of a circle in the"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure2-02';
UPDATE topics SET subtopics='["4.1 Sequences, including those given by a formula for the nth term and", "4.2 Understand and work with arithmetic sequences and series,", "4.3 Increasing sequences, decreasing sequences and periodic sequences.", "4.4 Understand and work with geometric sequences and series,", "4.5 Binomial expansion of (a + bx)n for positive integer n."]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure2-03';
UPDATE topics SET subtopics='["6.1 Knowledge and use of tan θ = sin and sin2 θ + cos2 θ = 1.", "6.2 Solution of simple trigonometric equations in a given interval."]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure2-04';
UPDATE topics SET subtopics='["5.1 y = ax and its graph. a > 0, a ≠ 1", "5.2 Laws of logarithms. To include loga (xy) ≡ loga x + log ay,", "5.3 The solution of equations of the form ax = b."]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure2-05';
UPDATE topics SET subtopics='["7.1 Applications of differentiation to maxima and minima and stationary"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure2-06';
UPDATE topics SET subtopics='["1.1 Simplification of rational expressions including factorising", "1.2 Definition of a function. Domain and range of functions.", "1.3 The modulus function. Students should be able to sketch the graphs of", "1.4 Combinations of the transformations y = f(x) as represented by y = af(x),"]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure3-01';
UPDATE topics SET subtopics='["2.1 Knowledge of secant, cosecant and cotangent and of arcsin, arccos and", "2.2 Knowledge and use of sec2 θ = 1 + tan2 θ and", "2.3 Knowledge and use of double angle formulae; use of formulae for"]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure3-02';
UPDATE topics SET subtopics='["4.1 Differentiation of ekx, ln kx, sin kx, cos kx, tan kx and their sums and", "4.2 Differentiation using the product rule, the quotient rule and the chain", "4.3 The use of For example, finding d x for x = sin 3y", "4.4 Understand and use exponential growth and decay."]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure3-03';
UPDATE topics SET subtopics='["5.1 Integration of ekx, 1 nx , sin kx, cos kx", "5.2 Integration by recognition of known derivatives to include"]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure3-04';
UPDATE topics SET subtopics='["6.1 Location of roots of f(x) = 0 by considering changes of sign of f(x)", "6.2 Approximate solution of equations using simple iterative methods,"]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure3-05';
UPDATE topics SET subtopics='["6.1 Evaluation of volume of revolution. is required, but not π", "6.2 Simple cases of integration by substitution and integration by", "6.3 Simple cases of integration using partial fractions.", "6.4 Analytical solution of simple first order differential equations with", "6.5 Use integration to find the area under a curve given its parametric"]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure4-01';
UPDATE topics SET subtopics='["4.1 Binomial Series for any rational n. For | x | < b"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure4-02';
UPDATE topics SET subtopics='["3.1 Parametric equations of curves and conversion between cartesian and"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure4-03';
UPDATE topics SET subtopics='["5.1 Differentiation of simple functions defined implicitly or", "5.2 Formation of simple differential equations."]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-pure4-04';
UPDATE topics SET subtopics='["1.1 Definition of complex numbers in the form a + ib and", "1.2 Sum, product and quotient of complex numbers.", "1.3 Geometrical representation of complex numbers in the Argand", "1.4 Complex solutions of quadratic equations with real coefficients.", "1.5 Finding conjugate complex roots and a real root of a cubic equation", "1.6 Finding conjugate complex roots and/or real roots of a quartic"]', subtopics_count=6, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-01';
UPDATE topics SET subtopics='["2.1 Sum of roots and product of roots of a quadratic equation.", "2.2 Manipulation of expressions involving the sum of roots and", "2.3 Forming quadratic equations with new roots."]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-02';
UPDATE topics SET subtopics='["3.1 Equations of the form f(x) = 0 solved numerically by:"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-03';
UPDATE topics SET subtopics='["4.1 Cartesian equations for the parabola and rectangular hyperbola.", "4.2 Idea of parametric equation for parabola and rectangular hyperbola.", "4.3 The focus-directrix property of the parabola.", "4.4 Tangents and normals to these curves. Differentiation of y ="]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-04';
UPDATE topics SET subtopics='["5.1 Addition and subtraction of matrices.", "5.2 Multiplication of a matrix by a scalar.", "5.3 Products of matrices.", "5.4 Evaluation of 2 × 2 determinants. Singular and non-singular matrices.", "5.5 Inverse of 2 × 2 matrices. Use of the relation (AB)–1 = B–1A–1."]', subtopics_count=5, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-05';
UPDATE topics SET subtopics='["7.1 Summation of simple finite series. Students should be able to sum series such as"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-fmath1-06';
UPDATE topics SET subtopics='["1.1 Kinematics of a particle moving in a straight line when the acceleration"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech3-01';
UPDATE topics SET subtopics='["2.1 Elastic strings and springs. Hooke’s law.", "2.2 Energy stored in an elastic string or spring."]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech3-02';
UPDATE topics SET subtopics='["3.1 Newton’s laws of motion, for a particle moving in one dimension,", "3.2 Simple harmonic motion. Proof that a particle moves with simple harmonic motion in", "3.3 Oscillations of a particle attached to the end of an elastic string or"]', subtopics_count=3, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech3-03';
UPDATE topics SET subtopics='["4.1 Angular speed.", "4.2 Radial acceleration in circular motion. The forms rω 2 and", "4.3 Uniform motion of a particle moving in a horizontal circle.", "4.4 Motion of a particle in a vertical circle."]', subtopics_count=4, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-mech3-04';
UPDATE topics SET subtopics='["1.1 Distribution of linear combinations of independent Normal random"]', subtopics_count=1, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat3-01';
UPDATE topics SET subtopics='["2.1 Methods for collecting data. Simple random sampling. Use of random", "2.2 Other methods of sampling: stratified, systematic, quota."]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat3-02';
UPDATE topics SET subtopics='["4.1 The null and alternative hypotheses. The use of", "4.2 Degrees of freedom. Students will be expected to determine the degrees of"]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat3-04';
UPDATE topics SET subtopics='["5.1 Spearman’s rank correlation coefficient, its use, interpretation", "5.2 Testing the hypothesis that a correlation is zero."]', subtopics_count=2, updated_at=strftime('%s','now')*1000 WHERE id='topic-edx-ial-stat3-05';
