"""Generate comprehensive topic seeds for Edexcel IGCSE and Edexcel IAL from official specifications."""
from pathlib import Path

OUT_IGCSE = Path(__file__).with_name("0008_topics_edexcel_igcse.sql")
OUT_IAL = Path(__file__).with_name("0009_topics_edexcel_ial.sql")

# Topic schema:
# (id, subject_id, name, description, order_index, subtopics_count, difficulty_level, estimated_hours)

EDEXCEL_IGCSE_TOPICS = [
    # --- 4MA1: Mathematics A ---
    ("topic-edx-igcse-maths-a-01", "subj-edx-igcse-maths-a", "Numbers and the number system",
     "Integers, fractions, decimals, powers, roots, standard form, percentages, ratio, proportion, bounds, degree of accuracy, and surds.",
     1, 14, "medium", 12),
    ("topic-edx-igcse-maths-a-02", "subj-edx-igcse-maths-a", "Equations, formulae and identities",
     "Algebraic manipulation, expansion, factorisation, linear and quadratic equations, algebraic fractions, rearranging formulae, simultaneous equations, and inequalities.",
     2, 12, "hard", 14),
    ("topic-edx-igcse-maths-a-03", "subj-edx-igcse-maths-a", "Sequences, functions and graphs",
     "Arithmetic sequences, nth term, function notation, domain and range, composite and inverse functions, straight line graphs, gradients, and quadratic/cubic curve sketches.",
     3, 9, "medium", 10),
    ("topic-edx-igcse-maths-a-04", "subj-edx-igcse-maths-a", "Geometry and trigonometry",
     "Angles, polygons, parallel lines, circle theorems, constructions, Pythagoras theorem, sine/cosine rules, 3D trigonometry, and bearings.",
     4, 11, "hard", 12),
    ("topic-edx-igcse-maths-a-05", "subj-edx-igcse-maths-a", "Vectors and transformation geometry",
     "Column vectors, vector arithmetic, vector proofs of collinearity and parallel lines, reflections, rotations, translations, and enlargements.",
     5, 6, "hard", 8),
    ("topic-edx-igcse-maths-a-06", "subj-edx-igcse-maths-a", "Statistics and probability",
     "Averages, range, frequency polygons, cumulative frequency, histograms with unequal intervals, simple and combined probability, Venn diagrams, and tree diagrams.",
     6, 8, "medium", 8),
    ("topic-edx-igcse-maths-a-07", "subj-edx-igcse-maths-a", "Calculus",
     "Differentiation of polynomials, finding gradients, tangents and normals, stationary points, and kinematics applications.",
     7, 5, "hard", 8),

    # --- 4MB1: Mathematics B ---
    ("topic-edx-igcse-maths-b-01", "subj-edx-igcse-maths-b", "Number and sets",
     "Types of number, set theory and Venn diagrams, indices, standard form, fractions, decimals, percentages, ratio, proportion, and surds.",
     1, 10, "medium", 10),
    ("topic-edx-igcse-maths-b-02", "subj-edx-igcse-maths-b", "Algebra",
     "Algebraic operations, factorisation, algebraic fractions, formula manipulation, linear and quadratic equations, simultaneous equations, and inequalities.",
     2, 12, "hard", 14),
    ("topic-edx-igcse-maths-b-03", "subj-edx-igcse-maths-b", "Functions",
     "Function notation, domain and range, inverse functions, composite functions, and roots of functions.",
     3, 6, "medium", 8),
    ("topic-edx-igcse-maths-b-04", "subj-edx-igcse-maths-b", "Matrices",
     "Matrix operations, 2x2 matrix multiplication, identity matrix, determinants, inverse matrices, and transformations.",
     4, 6, "hard", 8),
    ("topic-edx-igcse-maths-b-05", "subj-edx-igcse-maths-b", "Geometry and mensuration",
     "Properties of polygons, symmetry, circle theorems, perimeter, area, volume, and surface area of prisms, cylinders, cones and spheres.",
     5, 9, "medium", 10),
    ("topic-edx-igcse-maths-b-06", "subj-edx-igcse-maths-b", "Trigonometry",
     "Trigonometric ratios, sine and cosine rules, area of a triangle, 2D and 3D geometric problems, and bearings.",
     6, 7, "hard", 8),
    ("topic-edx-igcse-maths-b-07", "subj-edx-igcse-maths-b", "Statistics and probability",
     "Mean, median, mode, quartiles, interquartile range, cumulative frequency, histograms, basic probability, tree diagrams, and conditional probability.",
     7, 8, "medium", 8),
    ("topic-edx-igcse-maths-b-08", "subj-edx-igcse-maths-b", "Vectors",
     "Vector notation, addition, subtraction, scalar multiplication, position vectors, and geometrical proofs using vectors.",
     8, 5, "hard", 7),
    ("topic-edx-igcse-maths-b-09", "subj-edx-igcse-maths-b", "Calculus",
     "Differentiation of powers of x, turning points, maxima and minima, integration of polynomials, and plane areas.",
     9, 6, "hard", 10),

    # --- 4PM1: Further Pure Mathematics ---
    ("topic-edx-igcse-fmaths-01", "subj-edx-igcse-fmaths", "Logarithmic functions and indices",
     "Laws of logarithms, change of base, exponential and logarithmic equations, and graph transformations.",
     1, 5, "medium", 8),
    ("topic-edx-igcse-fmaths-02", "subj-edx-igcse-fmaths", "Quadratic functions and inequalities",
     "Completing the square, roots of quadratic equations, sum and product of roots, and quadratic inequalities in one and two variables.",
     2, 6, "medium", 8),
    ("topic-edx-igcse-fmaths-03", "subj-edx-igcse-fmaths", "The remainder and factor theorems",
     "Polynomial division, remainder theorem, factor theorem, and solving cubic and quartic equations.",
     3, 4, "medium", 6),
    ("topic-edx-igcse-fmaths-04", "subj-edx-igcse-fmaths", "Binomial series",
     "Expansion of (1 + x)^n and (a + bx)^n for positive integral n, finding specific terms and coefficients.",
     4, 4, "medium", 6),
    ("topic-edx-igcse-fmaths-05", "subj-edx-igcse-fmaths", "Coordinate geometry",
     "Distance, midpoint, gradient, parallel and perpendicular lines, equations of straight lines, and coordinate geometry of circles.",
     5, 7, "hard", 9),
    ("topic-edx-igcse-fmaths-06", "subj-edx-igcse-fmaths", "Trigonometry",
     "Radian measure, arc length, sector area, exact trigonometric values, trigonometric identities, and compound angle formulae.",
     6, 8, "hard", 12),
    ("topic-edx-igcse-fmaths-07", "subj-edx-igcse-fmaths", "Differentiation",
     "Differentiation of standard functions, product rule, quotient rule, chain rule, rates of change, tangents, normals, and optimization.",
     7, 8, "hard", 12),
    ("topic-edx-igcse-fmaths-08", "subj-edx-igcse-fmaths", "Integration",
     "Indefinite and definite integrals, integration of standard algebraic and trigonometric functions, areas under and between curves, and volumes of revolution.",
     8, 7, "hard", 12),
    ("topic-edx-igcse-fmaths-09", "subj-edx-igcse-fmaths", "Vectors in two dimensions",
     "Magnitude and direction, vector algebra, scalar product, angle between two vectors, and geometric proofs.",
     9, 5, "hard", 8),

    # --- 4PH1: Physics ---
    ("topic-edx-igcse-phys-01", "subj-edx-igcse-phys", "Forces and motion",
     "Movement, position, speed, acceleration, forces, Newton's laws, friction, momentum, conservation of momentum, and moments.",
     1, 9, "medium", 12),
    ("topic-edx-igcse-phys-02", "subj-edx-igcse-phys", "Electricity",
     "Mains electricity, electrical safety, energy and voltage in circuits, electric charge, static electricity, current and resistance in circuits.",
     2, 8, "medium", 10),
    ("topic-edx-igcse-phys-03", "subj-edx-igcse-phys", "Waves",
     "Properties of waves, the electromagnetic spectrum, light, reflection, refraction, total internal reflection, sound waves, and ultrasound.",
     3, 8, "medium", 10),
    ("topic-edx-igcse-phys-04", "subj-edx-igcse-phys", "Energy resources and energy transfers",
     "Energy transfers, conservation of energy, work, power, kinetic and gravitational potential energy, efficiency, and energy resources.",
     4, 6, "easy", 8),
    ("topic-edx-igcse-phys-05", "subj-edx-igcse-phys", "Solids, liquids and gases",
     "Density, pressure, pressure in fluids, changes of state, specific heat capacity, and ideal gas molecules and laws.",
     5, 6, "medium", 8),
    ("topic-edx-igcse-phys-06", "subj-edx-igcse-phys", "Magnetism and electromagnetism",
     "Magnets, magnetic fields, electromagnetism, motor effect, electromagnetic induction, generators, and transformers.",
     6, 7, "hard", 10),
    ("topic-edx-igcse-phys-07", "subj-edx-igcse-phys", "Radioactivity and particles",
     "Atomic structure, ionising radiation, alpha, beta, gamma decay, half-life, uses and dangers of radiation, nuclear fission and fusion.",
     7, 6, "medium", 8),
    ("topic-edx-igcse-phys-08", "subj-edx-igcse-phys", "Astrophysics",
     "Motion in the universe, stellar evolution, classification of stars, cosmology, Big Bang theory, red-shift, and cosmic microwave background radiation.",
     8, 5, "easy", 6),

    # --- 4CH1: Chemistry ---
    ("topic-edx-igcse-chem-01", "subj-edx-igcse-chem", "Principles of chemistry",
     "States of matter, atomic structure, relative formula masses, chemical formulae and equations, ionic, covalent, and metallic bonding.",
     1, 10, "medium", 12),
    ("topic-edx-igcse-chem-02", "subj-edx-igcse-chem", "Inorganic chemistry",
     "The Periodic Table, group 1 alkali metals, group 7 halogens, atmospheric gases, reactivity series, extraction of metals, acids, alkalis, and chemical tests.",
     2, 11, "medium", 14),
    ("topic-edx-igcse-chem-03", "subj-edx-igcse-chem", "Physical chemistry",
     "Energetics, exothermic and endothermic reactions, rates of reaction, catalysts, reversible reactions, and dynamic equilibria.",
     3, 6, "hard", 10),
    ("topic-edx-igcse-chem-04", "subj-edx-igcse-chem", "Organic chemistry",
     "Introduction to organic chemistry, alkanes, alkenes, alcohols, carboxylic acids, esters, synthetic polymers, and condensation polymerisation.",
     4, 8, "hard", 12),

    # --- 4BI1: Biology ---
    ("topic-edx-igcse-bio-01", "subj-edx-igcse-bio", "The nature and variety of living organisms",
     "Characteristics of living organisms, eukaryotic and prokaryotic organisms, pathogen classification: bacteria, viruses, fungi, and protoctists.",
     1, 4, "easy", 6),
    ("topic-edx-igcse-bio-02", "subj-edx-igcse-bio", "Structures and functions in living organisms",
     "Cell structure, biological molecules, movement across membranes, nutrition in humans and plants, respiration, gas exchange, transport, excretion, and coordination.",
     2, 15, "medium", 16),
    ("topic-edx-igcse-bio-03", "subj-edx-igcse-bio", "Reproduction and inheritance",
     "Reproduction in plants and humans, cell division by mitosis and meiosis, patterns of inheritance, chromosomes, genes, and DNA structure.",
     3, 8, "hard", 12),
    ("topic-edx-igcse-bio-04", "subj-edx-igcse-bio", "Ecology and the environment",
     "The organism in the environment, feeding relationships, nutrient cycles (carbon, nitrogen), and human impact on ecosystems.",
     4, 6, "medium", 8),
    ("topic-edx-igcse-bio-05", "subj-edx-igcse-bio", "Use of biological resources",
     "Food production using crop plants and microorganisms, fish farming, selective breeding, genetic modification, and cloning.",
     5, 6, "medium", 8),

    # --- 4HB1: Human Biology ---
    ("topic-edx-igcse-human-bio-01", "subj-edx-igcse-human-bio", "Cells and tissues",
     "Cell structures, organelles, levels of organisation, and differentiation of human specialised tissues.",
     1, 3, "easy", 5),
    ("topic-edx-igcse-human-bio-02", "subj-edx-igcse-human-bio", "Biological molecules and movement of substances",
     "Carbohydrates, lipids, proteins, enzymes, diffusion, osmosis, and active transport mechanisms.",
     2, 4, "medium", 6),
    ("topic-edx-igcse-human-bio-03", "subj-edx-igcse-human-bio", "Bones, muscles and joints",
     "Skeletal structure, functions of skeleton, antagonistic muscle pairs, synovial joints, and locomotion.",
     3, 4, "easy", 6),
    ("topic-edx-igcse-human-bio-04", "subj-edx-igcse-human-bio", "Nutrition and digestion",
     "Dietary components, balanced diet, digestive tract anatomy, mechanical and chemical digestion, and absorption.",
     4, 5, "medium", 8),
    ("topic-edx-igcse-human-bio-05", "subj-edx-igcse-human-bio", "Respiration and gas exchange",
     "Aerobic and anaerobic respiration, mechanics of breathing, respiratory volumes, and gas exchange adaptations.",
     5, 4, "medium", 6),
    ("topic-edx-igcse-human-bio-06", "subj-edx-igcse-human-bio", "Internal transport and circulation",
     "Heart anatomy, cardiac cycle, blood vessels, composition of blood, blood groups, and lymphatic system.",
     6, 5, "medium", 8),
    ("topic-edx-igcse-human-bio-07", "subj-edx-igcse-human-bio", "Disease, immunity and healthcare",
     "Infectious vs non-infectious diseases, immune responses, vaccinations, antibiotics, and community hygiene.",
     7, 5, "medium", 8),
    ("topic-edx-igcse-human-bio-08", "subj-edx-igcse-human-bio", "Excretion and homeostasis",
     "Kidney structure and function, nephron processes, osmoregulation, dialysis, and skin temperature regulation.",
     8, 4, "hard", 7),
    ("topic-edx-igcse-human-bio-09", "subj-edx-igcse-human-bio", "Coordination, response and senses",
     "Nervous system, reflex arcs, structure of the eye and ear, endocrine system, and hormones.",
     9, 5, "hard", 8),
    ("topic-edx-igcse-human-bio-10", "subj-edx-igcse-human-bio", "Reproduction, inheritance and genetics",
     "Human reproductive systems, gametogenesis, fertilisation, pregnancy, birth, genetics, cell division, and inheritance.",
     10, 6, "hard", 10),

    # --- 4CP0: Computer Science ---
    ("topic-edx-igcse-cs-01", "subj-edx-igcse-cs", "Problem solving",
     "Algorithms, decomposition, abstraction, flowcharts, pseudocode, truth tables, and searching and sorting algorithms.",
     1, 6, "medium", 10),
    ("topic-edx-igcse-cs-02", "subj-edx-igcse-cs", "Programming",
     "Data types, variables, arithmetic and relational operators, sequence, selection, iteration, arrays, functions, and subroutines.",
     2, 8, "hard", 16),
    ("topic-edx-igcse-cs-03", "subj-edx-igcse-cs", "Data representation",
     "Binary and hexadecimal number systems, character encoding (ASCII, Unicode), representation of images, sound, and data compression.",
     3, 5, "medium", 8),
    ("topic-edx-igcse-cs-04", "subj-edx-igcse-cs", "Computer systems",
     "Hardware and software, CPU architecture (Von Neumann), fetch-decode-execute cycle, secondary storage, and system software.",
     4, 6, "medium", 8),
    ("topic-edx-igcse-cs-05", "subj-edx-igcse-cs", "Communication and the internet",
     "Network topologies, client-server vs peer-to-peer, protocols (TCP/IP, HTTP, HTTPS), security vulnerabilities, and network security defences.",
     5, 6, "medium", 8),
    ("topic-edx-igcse-cs-06", "subj-edx-igcse-cs", "The bigger picture",
     "Emerging technologies, artificial intelligence, environmental impacts, ethical considerations, and legal frameworks.",
     6, 4, "easy", 6),

    # --- 4IT1: Information and Communication Technology (ICT) ---
    ("topic-edx-igcse-ict-01", "subj-edx-igcse-ict", "Digital Devices",
     "Types of digital devices, memory and storage, input and output peripherals, performance factors, and device selection.",
     1, 5, "easy", 6),
    ("topic-edx-igcse-ict-02", "subj-edx-igcse-ict", "Connectivity",
     "Wired and wireless communication, network types (LAN, WAN, PAN), transmission media, broadband, and mobile connectivity.",
     2, 5, "medium", 6),
    ("topic-edx-igcse-ict-03", "subj-edx-igcse-ict", "Operating Online",
     "The worldwide web, search techniques, communication tools, cloud computing, and online safety, security and legislation.",
     3, 6, "medium", 8),
    ("topic-edx-igcse-ict-04", "subj-edx-igcse-ict", "Online Goods and Services",
     "Cloud and hosted software, online banking, retail, and entertainment, and the impacts of digital transactions on businesses and consumers.",
     4, 4, "easy", 6),
    ("topic-edx-igcse-ict-05", "subj-edx-igcse-ict", "Applying ICT",
     "Impact of ICT on society, remote working, digital divide, environmental factors, and health and safety at work.",
     5, 4, "easy", 6),
    ("topic-edx-igcse-ict-06", "subj-edx-igcse-ict", "Software Skills (Practical)",
     "Word processing, presentations, spreadsheet modelling with complex formulae and lookups, database design, queries and reports, and web authoring.",
     6, 8, "hard", 16),

    # --- 4EB1: English Language B ---
    ("topic-edx-igcse-eng-b-01", "subj-edx-igcse-eng-b", "Reading: Non-fiction and Unseen Texts",
     "Critical reading, analysis of language, structure, perspective, tone, purpose, and comparative synthesis of unseen non-fiction texts.",
     1, 6, "medium", 12),
    ("topic-edx-igcse-eng-b-02", "subj-edx-igcse-eng-b", "Directed Writing",
     "Producing adapted texts (articles, speeches, letters) based on stimulus material, transforming tone, and addressing targeted audiences.",
     2, 5, "hard", 12),
    ("topic-edx-igcse-eng-b-03", "subj-edx-igcse-eng-b", "Continuous Composition",
     "Narrative, descriptive, discursive, and argumentative writing, incorporating advanced vocabulary, varied syntax, and deliberate rhetorical devices.",
     3, 6, "hard", 12),

    # --- 4ES1: English as a Second Language (ESL) ---
    ("topic-edx-igcse-esl-01", "subj-edx-igcse-esl", "Reading skills",
     "Skimming, scanning, understanding main ideas, identifying detail, recognising attitude, and deducing meaning from context.",
     1, 5, "medium", 10),
    ("topic-edx-igcse-esl-02", "subj-edx-igcse-esl", "Writing skills",
     "Formal and informal letters, emails, articles, and summaries, using appropriate register, grammar, and paragraph organisation.",
     2, 6, "hard", 14),
    ("topic-edx-igcse-esl-03", "subj-edx-igcse-esl", "Listening skills",
     "Listening for global meaning, identifying factual details, note-taking from spoken texts, interviews, and public announcements.",
     3, 5, "medium", 10),
    ("topic-edx-igcse-esl-04", "subj-edx-igcse-esl", "Speaking and communication",
     "Fluency, interaction, pronunciation, structured discussion, delivering topic presentations, and sustaining dialogue.",
     4, 4, "medium", 8),

    # --- 4EC1: Economics ---
    ("topic-edx-igcse-econ-01", "subj-edx-igcse-econ", "The market system",
     "The economic problem, factors of production, demand and supply curves, equilibrium price, price elasticity of demand and supply, and mixed economies.",
     1, 8, "medium", 10),
    ("topic-edx-igcse-econ-02", "subj-edx-igcse-econ", "Business economics",
     "Production, productivity, economies and diseconomies of scale, revenues, costs, profits, competitive vs monopoly markets, and labour market dynamics.",
     2, 7, "hard", 10),
    ("topic-edx-igcse-econ-03", "subj-edx-igcse-econ", "Government and the economy",
     "Macroeconomic objectives: economic growth, low unemployment, price stability, fiscal policy, monetary policy, and supply-side policy.",
     3, 7, "hard", 12),
    ("topic-edx-igcse-econ-04", "subj-edx-igcse-econ", "The global economy",
     "Globalisation, international trade, protectionism, exchange rates, balance of payments, and economic development.",
     4, 6, "medium", 10),

    # --- 4BS1: Business ---
    ("topic-edx-igcse-biz-01", "subj-edx-igcse-biz", "Business activity and influences",
     "Business enterprise, classification of businesses, enterprise objectives, stakeholders, external economic influences, and business ethics.",
     1, 7, "easy", 8),
    ("topic-edx-igcse-biz-02", "subj-edx-igcse-biz", "People in business",
     "Organisational structure, recruitment, selection, training, motivation theories, and management styles.",
     2, 6, "medium", 8),
    ("topic-edx-igcse-biz-03", "subj-edx-igcse-biz", "Business finance",
     "Sources of finance, cash flow forecasting, working capital, break-even analysis, statement of comprehensive income, and financial ratios.",
     3, 8, "hard", 12),
    ("topic-edx-igcse-biz-04", "subj-edx-igcse-biz", "Marketing",
     "Market research, market segmentation, marketing mix (product, price, place, promotion), product life cycle, and digital marketing.",
     4, 7, "medium", 10),
    ("topic-edx-igcse-biz-05", "subj-edx-igcse-biz", "Business operations",
     "Production methods, lean production, quality assurance, supply chain management, and location decisions.",
     5, 6, "medium", 8),

    # --- 4AC1: Accounting ---
    ("topic-edx-igcse-acc-01", "subj-edx-igcse-acc", "The accounting environment",
     "Purpose of accounting, accounting equation, users of accounting information, and key accounting concepts and principles.",
     1, 5, "easy", 6),
    ("topic-edx-igcse-acc-02", "subj-edx-igcse-acc", "Introduction to bookkeeping",
     "Business documents, books of prime entry, double-entry ledger bookkeeping, cash book, and petty cash systems.",
     2, 7, "medium", 10),
    ("topic-edx-igcse-acc-03", "subj-edx-igcse-acc", "Introduction to control processes",
     "Trial balance, bank reconciliation statements, control accounts, and correction of errors using the journal.",
     3, 6, "hard", 10),
    ("topic-edx-igcse-acc-04", "subj-edx-igcse-acc", "Preparation of financial statements",
     "Income statements and statements of financial position for sole traders, service businesses, and partnerships.",
     4, 8, "hard", 14),
    ("topic-edx-igcse-acc-05", "subj-edx-igcse-acc", "Accounting for end of period adjustments",
     "Depreciation methods (straight-line, reducing balance), irrecoverable debts, allowance for doubtful debts, accruals, and prepayments.",
     5, 6, "hard", 10),
    ("topic-edx-igcse-acc-06", "subj-edx-igcse-acc", "Analysis and interpretation of accounts",
     "Profitability ratios, liquidity ratios, efficiency ratios, capital employed, and limitation of financial ratios.",
     6, 5, "medium", 8),
]

EDEXCEL_IAL_TOPICS = [
    # === PURE MATHEMATICS 1 (WMA11) ===
    ("topic-edx-ial-pure1-01", "subj-edx-ial-pure1", "Algebra and functions",
     "Indices, surds, quadratic equations, completing the square, discriminant, simultaneous equations, inequalities, and cubic polynomial sketches.",
     1, 8, "medium", 12),
    ("topic-edx-ial-pure1-02", "subj-edx-ial-pure1", "Coordinate geometry in the (x, y) plane",
     "Equation of a line, gradient, parallel and perpendicular lines, line segment length, and midpoints.",
     2, 5, "medium", 8),
    ("topic-edx-ial-pure1-03", "subj-edx-ial-pure1", "Trigonometry",
     "Sine, cosine, and tangent ratios, exact values, trigonometric equations, identities (tan x = sin x / cos x, sin^2 x + cos^2 x = 1).",
     3, 6, "medium", 10),
    ("topic-edx-ial-pure1-04", "subj-edx-ial-pure1", "Differentiation",
     "Derivative of x^n, gradient of curves, tangents and normals, second derivatives, stationary points, and optimization.",
     4, 6, "hard", 12),
    ("topic-edx-ial-pure1-05", "subj-edx-ial-pure1", "Integration",
     "Indefinite integration of x^n, finding arbitrary constant using coordinates, and definite integrals under curves.",
     5, 5, "hard", 10),

    # === PURE MATHEMATICS 2 (WMA12) ===
    ("topic-edx-ial-pure2-01", "subj-edx-ial-pure2", "Proof and algebra",
     "Proof by deduction, exhaustion and counter-example; remainder and factor theorems; algebraic division.",
     1, 5, "medium", 8),
    ("topic-edx-ial-pure2-02", "subj-edx-ial-pure2", "Coordinate geometry of circles",
     "Equation of circle (x-a)^2 + (y-b)^2 = r^2, tangent and normal properties, and intersection of lines and circles.",
     2, 5, "medium", 8),
    ("topic-edx-ial-pure2-03", "subj-edx-ial-pure2", "Sequences and series",
     "Arithmetic and geometric progressions, general terms, sum of n terms, sum to infinity, and binomial expansion (a + bx)^n.",
     3, 7, "medium", 12),
    ("topic-edx-ial-pure2-04", "subj-edx-ial-pure2", "Trigonometry and radian measure",
     "Radian measure, arc length, sector area, sine and cosine rules in radians, and trigonometric equations across extended intervals.",
     4, 6, "hard", 10),
    ("topic-edx-ial-pure2-05", "subj-edx-ial-pure2", "Exponentials and logarithms",
     "Exponential functions, natural logarithm, laws of logarithms, solving equations, and modeling non-linear data using log transformations.",
     5, 6, "hard", 10),
    ("topic-edx-ial-pure2-06", "subj-edx-ial-pure2", "Differentiation and integration",
     "Differentiation of e^x and ln x, integration of standard exponential/trigonometric forms, and the trapezium rule.",
     6, 6, "hard", 10),

    # === PURE MATHEMATICS 3 (WMA13) ===
    ("topic-edx-ial-pure3-01", "subj-edx-ial-pure3", "Algebra and functions",
     "Modulus function, composite and inverse functions, combinations of transformations, and partial fractions with linear/repeated factors.",
     1, 6, "medium", 10),
    ("topic-edx-ial-pure3-02", "subj-edx-ial-pure3", "Trigonometric functions and identities",
     "Secant, cosecant, cotangent, compound and double angle formulae, R-addition formula (R cos(x +/- alpha)), and inverse trigonometric functions.",
     2, 7, "hard", 14),
    ("topic-edx-ial-pure3-03", "subj-edx-ial-pure3", "Differentiation",
     "Product rule, quotient rule, chain rule, differentiation of trigonometric, exponential and logarithmic functions.",
     3, 7, "hard", 14),
    ("topic-edx-ial-pure3-04", "subj-edx-ial-pure3", "Integration",
     "Integration by substitution, integration by parts, standard forms, and using partial fractions in integration.",
     4, 6, "hard", 14),
    ("topic-edx-ial-pure3-05", "subj-edx-ial-pure3", "Numerical methods",
     "Locating roots by sign change, fixed-point iteration x_{n+1} = g(x_n), cobweb and staircase diagrams.",
     5, 4, "medium", 6),

    # === PURE MATHEMATICS 4 (WMA14) ===
    ("topic-edx-ial-pure4-01", "subj-edx-ial-pure4", "Proof by contradiction",
     "Logical proof by contradiction (e.g. irrationality of root 2, infinitude of primes).",
     1, 3, "hard", 6),
    ("topic-edx-ial-pure4-02", "subj-edx-ial-pure4", "Algebra and binomial expansion",
     "Partial fractions with irreducible quadratic denominators, and binomial series (1 + x)^n for rational n.",
     2, 5, "medium", 8),
    ("topic-edx-ial-pure4-03", "subj-edx-ial-pure4", "Coordinate geometry and parametric equations",
     "Parametric equations of curves, converting to Cartesian form, tangents and normals to parametric curves.",
     3, 6, "hard", 10),
    ("topic-edx-ial-pure4-04", "subj-edx-ial-pure4", "Differentiation and integration",
     "Implicit differentiation, rates of change, advanced integration by parts and substitution, and volumes of revolution.",
     4, 8, "hard", 16),
    ("topic-edx-ial-pure4-05", "subj-edx-ial-pure4", "Differential equations",
     "Formulating differential equations, separation of variables, and general and particular solutions to real-world models.",
     5, 5, "hard", 10),
    ("topic-edx-ial-pure4-06", "subj-edx-ial-pure4", "Vectors in three dimensions",
     "3D vector geometry, vector equations of straight lines, angle between two lines, intersecting lines, and skew lines.",
     6, 6, "hard", 12),

    # === FURTHER PURE 1 (WFM01) ===
    ("topic-edx-ial-fmath1-01", "subj-edx-ial-fmath1", "Complex numbers",
     "Imaginary unit i, arithmetic of complex numbers, real and imaginary parts, complex conjugate, and roots of quadratic equations.",
     1, 5, "medium", 8),
    ("topic-edx-ial-fmath1-02", "subj-edx-ial-fmath1", "Roots of quadratic and cubic equations",
     "Relationships between roots and coefficients, and forming new equations whose roots are related to the original roots.",
     2, 4, "medium", 7),
    ("topic-edx-ial-fmath1-03", "subj-edx-ial-fmath1", "Numerical solutions of equations",
     "Interval bisection, linear interpolation, and the Newton-Raphson method.",
     3, 4, "medium", 6),
    ("topic-edx-ial-fmath1-04", "subj-edx-ial-fmath1", "Coordinate systems (Parabolas and Hyperbolas)",
     "Cartesian and parametric equations of parabolas and rectangular hyperbolas, tangents, and normals.",
     4, 5, "hard", 10),
    ("topic-edx-ial-fmath1-05", "subj-edx-ial-fmath1", "Matrix algebra",
     "Operations on 2x2 matrices, determinants, inverse matrices, and linear transformations in the 2D plane.",
     5, 6, "medium", 10),
    ("topic-edx-ial-fmath1-06", "subj-edx-ial-fmath1", "Series",
     "Summation of finite series using standard formulae for sum r, sum r^2, sum r^3, and method of differences.",
     6, 4, "medium", 8),
    ("topic-edx-ial-fmath1-07", "subj-edx-ial-fmath1", "Proof by mathematical induction",
     "Formulating and proving statements involving summation, divisibility, and matrix powers.",
     7, 4, "hard", 8),

    # === FURTHER PURE 2 (WFM02) ===
    ("topic-edx-ial-fmath2-01", "subj-edx-ial-fmath2", "Inequalities",
     "Algebraic and graphical solutions of rational inequalities containing modulus expressions.",
     1, 3, "medium", 6),
    ("topic-edx-ial-fmath2-02", "subj-edx-ial-fmath2", "Series and method of differences",
     "Higher summation of series using partial fractions and method of differences.",
     2, 4, "medium", 6),
    ("topic-edx-ial-fmath2-03", "subj-edx-ial-fmath2", "Further complex numbers",
     "Modulus-argument form, de Moivre's theorem, roots of complex numbers, and loci in the Argand diagram.",
     3, 6, "hard", 12),
    ("topic-edx-ial-fmath2-04", "subj-edx-ial-fmath2", "First and second order differential equations",
     "Integrating factors for first order equations, auxiliary equations, complementary functions and particular integrals for second order equations.",
     4, 7, "hard", 14),
    ("topic-edx-ial-fmath2-05", "subj-edx-ial-fmath2", "Maclaurin and Taylor series",
     "Derivation of series expansions for standard functions, and series solutions of differential equations.",
     5, 5, "hard", 10),
    ("topic-edx-ial-fmath2-06", "subj-edx-ial-fmath2", "Polar coordinates",
     "Polar equations r = f(theta), sketching polar curves, and calculating areas enclosed by polar curves.",
     6, 5, "hard", 10),

    # === FURTHER PURE 3 (WFM03) ===
    ("topic-edx-ial-fmath3-01", "subj-edx-ial-fmath3", "Hyperbolic functions",
     "Definitions of sinh, cosh, tanh, inverse hyperbolic functions, identities, and solving hyperbolic equations.",
     1, 6, "medium", 10),
    ("topic-edx-ial-fmath3-02", "subj-edx-ial-fmath3", "Further coordinate systems",
     "Cartesian, parametric, and polar equations of ellipses and hyperbolas, tangents, and eccentricities.",
     2, 6, "hard", 10),
    ("topic-edx-ial-fmath3-03", "subj-edx-ial-fmath3", "Differentiation and integration",
     "Differentiation of inverse trig and hyperbolic functions, reduction formulae, and arc lengths and surface areas of revolution.",
     3, 7, "hard", 14),
    ("topic-edx-ial-fmath3-04", "subj-edx-ial-fmath3", "Vectors",
     "Vector product, scalar triple product, line and plane equations in 3D, and perpendicular distances.",
     4, 6, "hard", 12),
    ("topic-edx-ial-fmath3-05", "subj-edx-ial-fmath3", "Further matrix algebra",
     "Eigenvalues and eigenvectors of 3x3 matrices, diagonalisation, and Cayley-Hamilton theorem.",
     5, 5, "hard", 12),

    # === MECHANICS 1 (WME01) ===
    ("topic-edx-ial-mech1-01", "subj-edx-ial-mech1", "Mathematical models in mechanics",
     "Assumptions, particles, light and inextensible strings, smooth and rough surfaces, and SI units.",
     1, 3, "easy", 4),
    ("topic-edx-ial-mech1-02", "subj-edx-ial-mech1", "Kinematics in a straight line",
     "Motion with constant acceleration (suvat), displacement-time and velocity-time graphs, and variable acceleration calculus.",
     2, 6, "medium", 10),
    ("topic-edx-ial-mech1-03", "subj-edx-ial-mech1", "Dynamics of a particle",
     "Newton's laws of motion, F = ma, resolving forces, friction, inclined planes, and connected particles with pulleys.",
     3, 7, "hard", 14),
    ("topic-edx-ial-mech1-04", "subj-edx-ial-mech1", "Statics of a particle",
     "Forces in equilibrium, resolving forces in two perpendicular directions, and friction in limiting equilibrium.",
     4, 5, "medium", 8),
    ("topic-edx-ial-mech1-05", "subj-edx-ial-mech1", "Moments",
     "Moment of a force about a point, principle of moments, and equilibrium of rigid bodies.",
     5, 5, "medium", 8),

    # === MECHANICS 2 (WME02) ===
    ("topic-edx-ial-mech2-01", "subj-edx-ial-mech2", "Kinematics in 2D and projectiles",
     "Projectiles in vertical and inclined planes, trajectory equation, range, and variable acceleration with vectors.",
     1, 6, "hard", 12),
    ("topic-edx-ial-mech2-02", "subj-edx-ial-mech2", "Centres of mass",
     "Centres of mass of particles, uniform laminae, framework wires, and equilibrium of suspended bodies.",
     2, 6, "medium", 10),
    ("topic-edx-ial-mech2-03", "subj-edx-ial-mech2", "Work, energy and power",
     "Kinetic energy, gravitational potential energy, work-energy principle, conservation of mechanical energy, and power.",
     3, 6, "medium", 10),
    ("topic-edx-ial-mech2-04", "subj-edx-ial-mech2", "Collisions and restitution",
     "Impulse, conservation of linear momentum, Newton's law of restitution, direct collisions, and successive impacts.",
     4, 6, "hard", 12),
    ("topic-edx-ial-mech2-05", "subj-edx-ial-mech2", "Statics of rigid bodies",
     "Ladders, rods resting against walls, friction at contact points, and sliding vs toppling.",
     5, 5, "hard", 10),

    # === MECHANICS 3 (WME03) ===
    ("topic-edx-ial-mech3-01", "subj-edx-ial-mech3", "Further kinematics",
     "Motion in a straight line with variable acceleration depending on time, displacement, or velocity.",
     1, 5, "hard", 10),
    ("topic-edx-ial-mech3-02", "subj-edx-ial-mech3", "Elastic strings and springs",
     "Hooke's law, modulus of elasticity, and elastic potential energy.",
     2, 5, "medium", 10),
    ("topic-edx-ial-mech3-03", "subj-edx-ial-mech3", "Further dynamics and simple harmonic motion",
     "Newton's second law with variable forces, SHM equations, period, amplitude, and oscillatory models.",
     3, 6, "hard", 14),
    ("topic-edx-ial-mech3-04", "subj-edx-ial-mech3", "Motion in a vertical circle",
     "Circular motion, energy conservation, tension, normal reaction, and complete circular revolutions.",
     4, 5, "hard", 12),
    ("topic-edx-ial-mech3-05", "subj-edx-ial-mech3", "Centres of mass of solids of revolution",
     "Using integration to find centres of mass of uniform solid bodies of revolution.",
     5, 4, "hard", 10),

    # === STATISTICS 1 (WST01) ===
    ("topic-edx-ial-stat1-01", "subj-edx-ial-stat1", "Representation and summary of data",
     "Histograms, stem-and-leaf diagrams, box plots, outliers, measures of central tendency, and variance and standard deviation.",
     1, 6, "medium", 10),
    ("topic-edx-ial-stat1-02", "subj-edx-ial-stat1", "Probability",
     "Venn diagrams, tree diagrams, laws of probability, independent events, mutually exclusive events, and conditional probability.",
     2, 6, "medium", 10),
    ("topic-edx-ial-stat1-03", "subj-edx-ial-stat1", "Correlation and regression",
     "Scatter diagrams, Pearson's product moment correlation coefficient, and least squares linear regression lines.",
     3, 5, "medium", 8),
    ("topic-edx-ial-stat1-04", "subj-edx-ial-stat1", "Discrete random variables",
     "Probability distributions, expected value E(X), variance Var(X), and linear transformations E(aX+b) and Var(aX+b).",
     4, 5, "medium", 8),
    ("topic-edx-ial-stat1-05", "subj-edx-ial-stat1", "The Normal distribution",
     "Continuous distributions, properties of the Normal distribution, standardisation Z = (X - mu)/sigma, and hypothesis tests.",
     5, 6, "hard", 12),

    # === STATISTICS 2 (WST02) ===
    ("topic-edx-ial-stat2-01", "subj-edx-ial-stat2", "The Binomial and Poisson distributions",
     "Conditions for Binomial and Poisson models, calculating probabilities, mean and variance, and Poisson approximations to Binomial.",
     1, 6, "medium", 10),
    ("topic-edx-ial-stat2-02", "subj-edx-ial-stat2", "Continuous random variables",
     "Probability density functions f(x), cumulative distribution functions F(x), expected values, variance, median, and modes.",
     2, 6, "hard", 12),
    ("topic-edx-ial-stat2-03", "subj-edx-ial-stat2", "Continuous distributions",
     "Continuous uniform (rectangular) distribution, mean, variance, and properties.",
     3, 4, "medium", 6),
    ("topic-edx-ial-stat2-04", "subj-edx-ial-stat2", "Hypothesis testing",
     "Null and alternative hypotheses, test statistics, significance levels, critical regions, Type I and Type II errors.",
     4, 6, "hard", 12),

    # === STATISTICS 3 (WST03) ===
    ("topic-edx-ial-stat3-01", "subj-edx-ial-stat3", "Combinations of random variables",
     "Distribution of sums and differences of independent Normal random variables.",
     1, 5, "medium", 8),
    ("topic-edx-ial-stat3-02", "subj-edx-ial-stat3", "Sampling and estimation",
     "Populations and samples, central limit theorem, unbiased estimators of mean and variance, and confidence intervals.",
     2, 6, "hard", 10),
    ("topic-edx-ial-stat3-03", "subj-edx-ial-stat3", "Hypothesis tests on mean and variance",
     "Testing population mean and difference between two independent population means.",
     3, 5, "hard", 10),
    ("topic-edx-ial-stat3-04", "subj-edx-ial-stat3", "Goodness of fit and contingency tables",
     "Chi-squared test, degrees of freedom, goodness of fit for uniform, binomial, and normal distributions, and contingency tables.",
     4, 6, "hard", 12),
    ("topic-edx-ial-stat3-05", "subj-edx-ial-stat3", "Rank correlation",
     "Spearman's rank correlation coefficient, tied ranks, and hypothesis testing for rank correlation.",
     5, 4, "medium", 8),

    # === DECISION MATHEMATICS 1 (WDM11) ===
    ("topic-edx-ial-dec1-01", "subj-edx-ial-dec1", "Algorithms",
     "Algorithm efficiency, bin packing (first fit, first fit decreasing), bubble sort, and quick sort.",
     1, 5, "easy", 8),
    ("topic-edx-ial-dec1-02", "subj-edx-ial-dec1", "Algorithms on graphs",
     "Graph terminology, Kruskal's and Prim's algorithms for minimum spanning trees, and Dijkstra's shortest path algorithm.",
     2, 6, "medium", 10),
    ("topic-edx-ial-dec1-03", "subj-edx-ial-dec1", "The route inspection problem (Chinese Postman)",
     "Eulerian and semi-Eulerian graphs, finding shortest inspection routes, and pairing odd degree vertices.",
     3, 4, "medium", 8),
    ("topic-edx-ial-dec1-04", "subj-edx-ial-dec1", "Critical path analysis",
     "Activity networks, precedence tables, dummy activities, forward/backward passes, critical activities, float, and Gantt charts.",
     4, 6, "hard", 12),
    ("topic-edx-ial-dec1-05", "subj-edx-ial-dec1", "Linear programming",
     "Formulating linear programs, graphical solution methods, objective line methods, and vertex methods.",
     5, 5, "hard", 10),
    ("topic-edx-ial-dec1-06", "subj-edx-ial-dec1", "Matchings",
     "Bipartite graphs, complete and maximal matchings, and the maximum matching algorithm.",
     6, 4, "medium", 8),

    # === PHYSICS UNITS 1-6 (WPH11-16) ===
    ("topic-edx-ial-phys1-01", "subj-edx-ial-phys1", "Mechanics",
     "Rectilinear motion, vector resolution, projectile motion, Newton's laws, momentum, work, energy, power, and efficiency.",
     1, 8, "medium", 16),
    ("topic-edx-ial-phys1-02", "subj-edx-ial-phys1", "Materials",
     "Density, fluid flow, laminar and turbulent flow, viscosity, Stokes' law, terminal velocity, Hooke's law, stress, strain, and Young modulus.",
     2, 7, "medium", 14),

    ("topic-edx-ial-phys2-01", "subj-edx-ial-phys2", "Waves and the particle nature of light",
     "Wave properties, transverse and longitudinal waves, refractive index, total internal reflection, diffraction, interference, polarization, and photoelectric effect.",
     1, 9, "hard", 18),
    ("topic-edx-ial-phys2-02", "subj-edx-ial-phys2", "Electric circuits",
     "Current, potential difference, resistance, Ohm's law, I-V characteristics, resistivity, electromotive force (e.m.f.), internal resistance, and potential dividers.",
     2, 7, "medium", 14),

    ("topic-edx-ial-phys3-01", "subj-edx-ial-phys3", "Practical Skills in Physics I",
     "Experimental design, measurement uncertainties, systematic and random errors, graphical analysis, and Core Practicals 1 to 9.",
     1, 6, "medium", 12),

    ("topic-edx-ial-phys4-01", "subj-edx-ial-phys4", "Further mechanics",
     "Circular motion, centripetal acceleration and force, impulse, and 2D conservation of linear momentum.",
     1, 5, "medium", 12),
    ("topic-edx-ial-phys4-02", "subj-edx-ial-phys4", "Electric and magnetic fields",
     "Coulomb's law, electric field strength, electric potential, capacitance, magnetic flux density, motor effect, electromagnetic induction, and Faraday's/Lenz's laws.",
     2, 8, "hard", 18),
    ("topic-edx-ial-phys4-03", "subj-edx-ial-phys4", "Nuclear and particle physics",
     "Atomic structure, Rutherford scattering, particle accelerators (cyclotrons, linacs), mass-energy equivalence E=mc^2, and fundamental particles (quarks, leptons).",
     3, 7, "hard", 14),

    ("topic-edx-ial-phys5-01", "subj-edx-ial-phys5", "Thermodynamics",
     "Specific heat capacity, specific latent heat, internal energy, kinetic theory of gases, and ideal gas equation pV = NkT.",
     1, 5, "medium", 12),
    ("topic-edx-ial-phys5-02", "subj-edx-ial-phys5", "Nuclear decay and radiation",
     "Alpha, beta, gamma radioactive decay, decay constant, half-life, exponential decay models, binding energy, and nuclear fission/fusion.",
     2, 6, "medium", 12),
    ("topic-edx-ial-phys5-03", "subj-edx-ial-phys5", "Oscillations",
     "Simple harmonic motion, displacement, velocity, acceleration relationships, energy in SHM, free and forced oscillations, and resonance.",
     3, 5, "hard", 12),
    ("topic-edx-ial-phys5-04", "subj-edx-ial-phys5", "Astrophysics and cosmology",
     "Gravitational fields, Newton's law of gravitation, planetary orbits, Kepler's laws, stellar luminosity, Stefan-Boltzmann law, Hubble's law, and the fate of the universe.",
     4, 6, "medium", 12),

    ("topic-edx-ial-phys6-01", "subj-edx-ial-phys6", "Practical Skills in Physics II",
     "Advanced experimental planning, multi-variable experiments, uncertainty propagation, percentage errors, critical evaluation, and Core Practicals 10 to 16.",
     1, 6, "hard", 14),

    # === CHEMISTRY UNITS 1-6 (WCH11-16) ===
    ("topic-edx-ial-chem1-01", "subj-edx-ial-chem1", "Formulae, equations and amount of substance",
     "The mole, Avogadro constant, reacting masses, gas volumes, solution stoichiometry, atom economy, and percentage yield.",
     1, 6, "medium", 10),
    ("topic-edx-ial-chem1-02", "subj-edx-ial-chem1", "Atomic structure and the periodic table",
     "Isotopes, mass spectrometry, electronic configurations, and trends in first ionisation energy across periods and down groups.",
     2, 5, "medium", 8),
    ("topic-edx-ial-chem1-03", "subj-edx-ial-chem1", "Bonding and structure",
     "Ionic bonding, covalent bonding, metallic bonding, giant vs molecular lattices, electronegativity, and bond polarity.",
     3, 6, "medium", 10),
    ("topic-edx-ial-chem1-04", "subj-edx-ial-chem1", "Introductory organic chemistry and alkanes",
     "Nomenclature, functional groups, structural isomerism, fractional distillation of crude oil, and free-radical substitution of alkanes.",
     4, 6, "medium", 10),
    ("topic-edx-ial-chem1-05", "subj-edx-ial-chem1", "Alkenes",
     "Electrophilic addition reactions of alkenes, carbocation stability, Markovnikov's rule, and addition polymerisation.",
     5, 5, "hard", 10),

    ("topic-edx-ial-chem2-01", "subj-edx-ial-chem2", "Energetics",
     "Enthalpy changes, Hess's Law, bond enthalpies, standard enthalpy of formation and combustion, and calorimetry.",
     1, 6, "medium", 10),
    ("topic-edx-ial-chem2-02", "subj-edx-ial-chem2", "Intermolecular forces",
     "London dispersion forces, dipole-dipole interactions, hydrogen bonding, and physical properties of liquids and solids.",
     2, 5, "medium", 8),
    ("topic-edx-ial-chem2-03", "subj-edx-ial-chem2", "Redox chemistry and groups 1, 2 and 7",
     "Oxidation numbers, redox reactions, trends in reactivity, thermal stability of carbonates and nitrates, and halogen chemistry.",
     3, 7, "medium", 12),
    ("topic-edx-ial-chem2-04", "subj-edx-ial-chem2", "Introduction to kinetics and equilibria",
     "Collision theory, activation energy, Maxwell-Boltzmann distribution, catalysts, dynamic equilibrium, and Le Chatelier's principle.",
     4, 6, "medium", 10),
    ("topic-edx-ial-chem2-05", "subj-edx-ial-chem2", "Organic chemistry: alcohols and halogenoalkanes",
     "Classification of alcohols, oxidation reactions, nucleophilic substitution of halogenoalkanes (SN1 vs SN2), elimination, and infrared spectroscopy.",
     5, 8, "hard", 14),

    ("topic-edx-ial-chem3-01", "subj-edx-ial-chem3", "Practical Skills in Chemistry I",
     "Volumetric titrations, qualitative organic and inorganic analysis, enthalpy determination, and Core Practicals 1 to 8.",
     1, 6, "medium", 12),

    ("topic-edx-ial-chem4-01", "subj-edx-ial-chem4", "Kinetics",
     "Rate equations, order of reaction, rate constant k, Arrhenius equation, and reaction mechanisms with rate-determining step.",
     1, 6, "hard", 12),
    ("topic-edx-ial-chem4-02", "subj-edx-ial-chem4", "Entropy and energetics",
     "Lattice energy, Born-Haber cycles, enthalpy of solution and hydration, entropy changes, and Gibbs free energy Delta G.",
     2, 6, "hard", 12),
    ("topic-edx-ial-chem4-03", "subj-edx-ial-chem4", "Chemical equilibria",
     "Equilibrium constant expressions Kc and Kp, calculating equilibrium compositions, and effect of temperature on equilibrium constants.",
     3, 5, "medium", 10),
    ("topic-edx-ial-chem4-04", "subj-edx-ial-chem4", "Acid-base equilibria",
     "Bronsted-Lowry theory, pH calculations, ionic product of water Kw, acid dissociation constant Ka, buffer solutions, and titration curves.",
     4, 7, "hard", 14),
    ("topic-edx-ial-chem4-05", "subj-edx-ial-chem4", "Organic chemistry: carbonyls, carboxylic acids and chirality",
     "Aldehydes, ketones, nucleophilic addition, optical isomerism, carboxylic acids, acyl chlorides, esters, and polyesters.",
     5, 8, "hard", 14),

    ("topic-edx-ial-chem5-01", "subj-edx-ial-chem5", "Redox equilibria",
     "Standard electrode potentials, electrochemical cells, feasibility of reactions, and fuel cells.",
     1, 5, "medium", 10),
    ("topic-edx-ial-chem5-02", "subj-edx-ial-chem5", "Transition metals and their chemistry",
     "Electronic configurations, variable oxidation states, complex ions, ligand exchange, catalytic activity, and colour of complexes.",
     2, 7, "hard", 14),
    ("topic-edx-ial-chem5-03", "subj-edx-ial-chem5", "Organic chemistry: arenes and nitrogen compounds",
     "Benzene structure and stability, electrophilic aromatic substitution, amines, amides, amino acids, and condensation polymers.",
     3, 7, "hard", 14),
    ("topic-edx-ial-chem5-04", "subj-edx-ial-chem5", "Organic synthesis and NMR spectroscopy",
     "Multi-step synthetic routes, carbon-13 NMR, and proton NMR spectroscopy with splitting patterns.",
     4, 6, "hard", 14),

    ("topic-edx-ial-chem6-01", "subj-edx-ial-chem6", "Practical Skills in Chemistry II",
     "Preparation of organic solids and liquids, multi-step synthesis, advanced spectroscopy, and Core Practicals 9 to 16.",
     1, 6, "hard", 14),

    # === BIOLOGY UNITS 1-6 (WBI11-16) ===
    ("topic-edx-ial-bio1-01", "subj-edx-ial-bio1", "Biological molecules",
     "Water properties, carbohydrates (monosaccharides, disaccharides, polysaccharides), lipids, proteins, and enzyme kinetics.",
     1, 6, "medium", 12),
    ("topic-edx-ial-bio1-02", "subj-edx-ial-bio1", "Cardiovascular health and transport",
     "Circulatory systems, blood vessels, cardiac cycle, atherosclerosis, risk factors for cardiovascular disease, and anticoagulants.",
     2, 6, "medium", 12),
    ("topic-edx-ial-bio1-03", "subj-edx-ial-bio1", "Gene expression and inheritance",
     "DNA and RNA structure, transcription and translation, genetic mutations, cystic fibrosis, and genetic screening.",
     3, 6, "hard", 14),

    ("topic-edx-ial-bio2-01", "subj-edx-ial-bio2", "Cell structure and division",
     "Ultrastructure of eukaryotic and prokaryotic cells, mitosis, the cell cycle, stem cells, and cell differentiation.",
     1, 6, "medium", 10),
    ("topic-edx-ial-bio2-02", "subj-edx-ial-bio2", "Sexual reproduction and development",
     "Meiosis, gametogenesis, fertilisation in mammals and flowering plants, and epigenetic modification.",
     2, 6, "hard", 12),
    ("topic-edx-ial-bio2-03", "subj-edx-ial-bio2", "Biodiversity and conservation",
     "Classification and phylogeny, species richness, heterozygosity index, adaptations, and in situ and ex situ conservation.",
     3, 5, "easy", 8),

    ("topic-edx-ial-bio3-01", "subj-edx-ial-bio3", "Practical Skills in Biology I",
     "Microscopy, calibration, quantitative enzyme experiments, plant tissue investigation, and Core Practicals 1 to 9.",
     1, 6, "medium", 12),

    ("topic-edx-ial-bio4-01", "subj-edx-ial-bio4", "Photosynthesis and energy flow",
     "Chloroplast structure, light-dependent and light-independent reactions, limiting factors, and trophic efficiency.",
     1, 6, "hard", 12),
    ("topic-edx-ial-bio4-02", "subj-edx-ial-bio4", "Ecosystems and climate change",
     "Ecological succession, carbon cycle, greenhouse effect, evidence for climate change, and evolutionary selection pressures.",
     2, 6, "medium", 10),
    ("topic-edx-ial-bio4-03", "subj-edx-ial-bio4", "Microbiology and infection",
     "Bacterial growth phases, pathogenic mechanisms of viruses (HIV, TB), non-specific immune defenses, and antibody-mediated immunity.",
     3, 7, "hard", 14),
    ("topic-edx-ial-bio4-04", "subj-edx-ial-bio4", "Forensic biology",
     "Post-mortem timeline estimation (rigor mortis, body temperature), DNA profiling, and PCR amplification.",
     4, 4, "medium", 8),

    ("topic-edx-ial-bio5-01", "subj-edx-ial-bio5", "Respiration and muscle physiology",
     "Glycolysis, Krebs cycle, oxidative phosphorylation, lactate metabolism, skeletal muscle contraction, and sliding filament theory.",
     1, 7, "hard", 14),
    ("topic-edx-ial-bio5-02", "subj-edx-ial-bio5", "Homeostasis and the internal environment",
     "Negative feedback loops, kidney gross structure and nephron function, and hormonal control of blood water potential.",
     2, 6, "hard", 12),
    ("topic-edx-ial-bio5-03", "subj-edx-ial-bio5", "Coordination, nervous systems and brain",
     "Action potentials, synaptic transmission, sensory receptors, brain anatomy, fMRI imaging, and plant phytochrome responses.",
     3, 7, "hard", 14),
    ("topic-edx-ial-bio5-04", "subj-edx-ial-bio5", "Gene technology and ethics",
     "Recombinant DNA technology, gene therapy, genome sequencing, genetically modified organisms, and ethical controversies.",
     4, 5, "medium", 10),

    ("topic-edx-ial-bio6-01", "subj-edx-ial-bio6", "Practical Skills in Biology II",
     "Scientific experimental design, statistical testing (t-test, chi-squared, Mann-Whitney), evaluation of biological methodologies, and Core Practicals 10 to 18.",
     1, 6, "hard", 14),

    # === INFORMATION TECHNOLOGY UNITS 1-4 (WIT11-14) ===
    ("topic-edx-ial-it1-01", "subj-edx-ial-it1", "Hardware and software",
     "Components of computer systems, operating systems, utility software, open-source vs proprietary, and emerging hardware.",
     1, 5, "medium", 10),
    ("topic-edx-ial-it1-02", "subj-edx-ial-it1", "Networks and the Internet",
     "Network topologies, protocols, data transmission methods, packet switching, cloud computing, and wireless standards.",
     2, 6, "medium", 12),
    ("topic-edx-ial-it1-03", "subj-edx-ial-it1", "Enterprise IT and data security",
     "Impact of IT on business organizations, security threats, cryptography, disaster recovery, and legal and ethical considerations.",
     3, 6, "medium", 12),

    ("topic-edx-ial-it2-01", "subj-edx-ial-it2", "Digital relationships and databases",
     "Relational database design, entity relationship diagrams (ERDs), normalisation (1NF, 2NF, 3NF), and SQL queries.",
     1, 7, "hard", 16),
    ("topic-edx-ial-it2-02", "subj-edx-ial-it2", "Spreadsheet modelling",
     "Advanced spreadsheet functions (INDEX/MATCH, nested IFs), what-if analysis, macros, and financial and data modelling.",
     2, 6, "hard", 14),

    ("topic-edx-ial-it3-01", "subj-edx-ial-it3", "The impact of technology and project management",
     "Project management methodologies (Agile, Waterfall), critical path analysis, Gantt charts, and managing technological change.",
     1, 6, "medium", 12),
    ("topic-edx-ial-it3-02", "subj-edx-ial-it3", "Big data, cloud and cybersecurity",
     "Data analytics, big data characteristics, cloud architectures, penetration testing, digital forensics, and international cyber legislation.",
     2, 7, "hard", 16),

    ("topic-edx-ial-it4-01", "subj-edx-ial-it4", "Advanced database systems",
     "Complex SQL programming, database indexing, transactions and ACID compliance, and distributed database systems.",
     1, 6, "hard", 16),
    ("topic-edx-ial-it4-02", "subj-edx-ial-it4", "Practical technical project",
     "Requirements gathering, system architecture specification, implementation, testing regimes, user documentation, and technical evaluation.",
     2, 6, "hard", 18),

    # === COMPUTER SCIENCE UNITS 1-4 (WCP01-04) ===
    ("topic-edx-ial-cs1-01", "subj-edx-ial-cs1", "Problem solving and algorithms",
     "Decomposition, abstraction, algorithm design with pseudocode, trace tables, and searching/sorting algorithms.",
     1, 6, "medium", 12),
    ("topic-edx-ial-cs1-02", "subj-edx-ial-cs1", "Data representation and computer architecture",
     "Binary arithmetic, two's complement, floating point numbers, Von Neumann architecture, CPU components, and memory management.",
     2, 7, "hard", 14),

    ("topic-edx-ial-cs2-01", "subj-edx-ial-cs2", "Software development and data structures",
     "Arrays, stacks, queues, linked lists, trees, software life cycle models, and program testing regimes.",
     1, 7, "hard", 16),
    ("topic-edx-ial-cs2-02", "subj-edx-ial-cs2", "Networking and system software",
     "OS management of processes and memory, translators (compilers, interpreters, assemblers), network models (OSI, TCP/IP), and network security.",
     2, 7, "hard", 16),

    ("topic-edx-ial-cs3-01", "subj-edx-ial-cs3", "Advanced algorithms and computation",
     "Big-O notation, algorithm complexity, tree traversal (pre/in/post-order), graph algorithms (Dijkstra, A*), and recursive algorithms.",
     1, 8, "hard", 18),
    ("topic-edx-ial-cs3-02", "subj-edx-ial-cs3", "Logic and programming paradigms",
     "Boolean algebra, Karnaugh maps, logic gates, object-oriented programming (OOP), functional programming, and concurrent processing.",
     2, 7, "hard", 18),

    ("topic-edx-ial-cs4-01", "subj-edx-ial-cs4", "Databases, big data and web systems",
     "Relational models, SQL DDL/DML, normalisation, NoSQL databases, web client-server architecture, and API design.",
     1, 7, "hard", 16),
    ("topic-edx-ial-cs4-02", "subj-edx-ial-cs4", "Machine learning and emerging technologies",
     "Supervised/unsupervised learning, neural networks, ethical dilemmas in AI, quantum computing overviews, and cybersecurity.",
     2, 6, "medium", 14),

    # === ECONOMICS UNITS 1-4 (WEC11-14) ===
    ("topic-edx-ial-econ1-01", "subj-edx-ial-econ1", "Introductory microeconomics",
     "Scarcity, opportunity cost, production possibility frontiers, consumer behaviour, demand and supply, and elasticity.",
     1, 6, "medium", 12),
    ("topic-edx-ial-econ1-02", "subj-edx-ial-econ1", "Market failure and government intervention",
     "Externalities, public goods, information asymmetry, indirect taxation, subsidies, price controls, and government failure.",
     2, 6, "hard", 14),

    ("topic-edx-ial-econ2-01", "subj-edx-ial-econ2", "Macroeconomic performance and policies",
     "Economic growth, inflation, unemployment, balance of payments, aggregate demand and aggregate supply (AD-AS) analysis.",
     1, 7, "medium", 14),
    ("topic-edx-ial-econ2-02", "subj-edx-ial-econ2", "Policy instruments and conflicts",
     "Fiscal policy, monetary policy, supply-side policies, and trade-offs between macroeconomic objectives.",
     2, 6, "hard", 14),

    ("topic-edx-ial-econ3-01", "subj-edx-ial-econ3", "Business growth and revenue, costs and profits",
     "Organic and inorganic business growth, mergers, law of diminishing returns, economies of scale, and profit maximisation.",
     1, 7, "hard", 16),
    ("topic-edx-ial-econ3-02", "subj-edx-ial-econ3", "Market structures and government regulation",
     "Perfect competition, monopolistic competition, oligopoly, game theory, monopoly, contestability, and competition policy.",
     2, 8, "hard", 18),

    ("topic-edx-ial-econ4-01", "subj-edx-ial-econ4", "Globalisation and international trade",
     "Patterns of global trade, comparative advantage, terms of trade, trading blocs, protectionism, and the World Trade Organization.",
     1, 7, "medium", 16),
    ("topic-edx-ial-econ4-02", "subj-edx-ial-econ4", "Poverty, inequality and developing economies",
     "Causes of poverty, inequality measures (Lorenz curve, Gini coefficient), development indicators (HDI), foreign aid, and macroeconomic financial markets.",
     2, 7, "hard", 16),

    # === BUSINESS UNITS 1-4 (WBS11-14) ===
    ("topic-edx-ial-biz1-01", "subj-edx-ial-biz1", "Marketing and customer needs",
     "Market analysis, customer orientation, market research, marketing mix, branding, and dynamic markets.",
     1, 6, "easy", 10),
    ("topic-edx-ial-biz1-02", "subj-edx-ial-biz1", "Managing people and leadership",
     "Recruitment, training, organisational structures, leadership styles, motivation in theory and practice, and employee relations.",
     2, 6, "medium", 12),

    ("topic-edx-ial-biz2-01", "subj-edx-ial-biz2", "Raising and managing finance",
     "Internal and external sources of finance, working capital, cash flow forecasting, and break-even analysis.",
     1, 6, "hard", 14),
    ("topic-edx-ial-biz2-02", "subj-edx-ial-biz2", "Resource management and external influences",
     "Production methods, capacity utilisation, lean management, stock control, economic environment, and legal influences.",
     2, 7, "medium", 14),

    ("topic-edx-ial-biz3-01", "subj-edx-ial-biz3", "Business objectives and strategy",
     "Corporate objectives, strategic analysis (SWOT, PESTLE), Porter's five forces, Ansoff's matrix, and competitive advantage.",
     1, 6, "medium", 14),
    ("topic-edx-ial-biz3-02", "subj-edx-ial-biz3", "Business decision-making and change management",
     "Investment appraisal (NPV, ARR, payback), decision trees, critical path analysis, corporate culture, and managing change.",
     2, 7, "hard", 18),

    ("topic-edx-ial-biz4-01", "subj-edx-ial-biz4", "Global business and markets",
     "Globalisation, trade liberalization, growing economic power of emerging economies, and assessing country attractiveness.",
     1, 6, "medium", 14),
    ("topic-edx-ial-biz4-02", "subj-edx-ial-biz4", "Global marketing and multinational corporations",
     "Global marketing strategies, adaptation vs standardisation, multinational corporations, ethical dilemmas, and corporate governance.",
     2, 6, "hard", 16),

    # === ACCOUNTING UNITS 1-2 (WAC11-12) ===
    ("topic-edx-ial-acc1-01", "subj-edx-ial-acc1", "The accounting system and framework",
     "Financial accounting vs management accounting, the accounting cycle, double-entry bookkeeping, and accounting concepts and conventions.",
     1, 6, "medium", 12),
    ("topic-edx-ial-acc1-02", "subj-edx-ial-acc1", "Financial statements of sole traders and partnerships",
     "Income statements, statements of financial position, adjustments for depreciation and accruals, partnership appropriation, and changes in partnerships.",
     2, 8, "hard", 18),
    ("topic-edx-ial-acc1-03", "subj-edx-ial-acc1", "Costing systems and inventory",
     "Inventory valuation (FIFO, LIFO, AVCO), job costing, batch costing, and allocation and apportionment of overheads.",
     3, 6, "medium", 14),

    ("topic-edx-ial-acc2-01", "subj-edx-ial-acc2", "Corporate reporting and limited companies",
     "Published accounts of limited companies, share capital, reserves, debentures, and statements of changes in equity.",
     1, 7, "hard", 16),
    ("topic-edx-ial-acc2-02", "subj-edx-ial-acc2", "Statements of cash flows and ratio analysis",
     "Preparation of cash flow statements (IAS 7), profitability, liquidity, and investment ratios, and evaluation of corporate health.",
     2, 7, "hard", 16),
    ("topic-edx-ial-acc2-03", "subj-edx-ial-acc2", "Management accounting and budgeting",
     "Budgetary control, cash budgets, standard costing, variance analysis, marginal costing, and break-even decision making.",
     3, 7, "hard", 16),

    # === PSYCHOLOGY UNITS 1-4 (WPS01-04) ===
    ("topic-edx-ial-psych1-01", "subj-edx-ial-psych1", "Social psychology",
     "Conformity, obedience to authority (Milgram), social identity theory, prejudice, and realistic conflict theory.",
     1, 6, "medium", 14),
    ("topic-edx-ial-psych1-02", "subj-edx-ial-psych1", "Cognitive psychology",
     "Multi-store model of memory (Atkinson & Shiffrin), working memory model (Baddeley & Hitch), reconstructive memory, and explanations of forgetting.",
     2, 6, "medium", 14),

    ("topic-edx-ial-psych2-01", "subj-edx-ial-psych2", "Biological psychology",
     "Central nervous system, neurotransmission, brain localisation, hormones and aggression, evolutionary explanations, and circadian rhythms.",
     1, 6, "hard", 14),
    ("topic-edx-ial-psych2-02", "subj-edx-ial-psych2", "Learning theories and development",
     "Classical conditioning (Pavlov), operant conditioning (Skinner), social learning theory (Bandura), phobias, and systematic desensitisation.",
     2, 6, "medium", 14),

    ("topic-edx-ial-psych3-01", "subj-edx-ial-psych3", "Criminological psychology",
     "Theories of offending behaviour (biological, social), eyewitness testimony, cognitive interviews, and offender treatment programmes.",
     1, 6, "hard", 14),
    ("topic-edx-ial-psych3-02", "subj-edx-ial-psych3", "Health and developmental psychology",
     "Stress and illness, models of health behaviour, child cognitive development (Piaget, Vygotsky), and attachment theory (Bowlby).",
     2, 6, "medium", 14),

    ("topic-edx-ial-psych4-01", "subj-edx-ial-psych4", "Clinical psychology",
     "Diagnosis and classification systems (DSM, ICD), mental health disorders (schizophrenia, depression), and biological and psychological therapies.",
     1, 7, "hard", 16),
    ("topic-edx-ial-psych4-02", "subj-edx-ial-psych4", "Psychological skills and research methods",
     "Experimental design, sampling methods, descriptive and inferential statistics (Chi-squared, Mann-Whitney, Spearman), and ethical guidelines in psychological research.",
     2, 7, "hard", 16),
]


def generate_sql(topics, outfile, title):
    lines = [
        f"-- {outfile.name}",
        f"-- {title}",
        "",
        "INSERT OR IGNORE INTO topics (id, subject_id, name, description, order_index, subtopics_count, difficulty_level, estimated_hours, created_at, updated_at) VALUES"
    ]
    val_lines = []
    for t in topics:
        tid, sid, name, desc, idx, sub_cnt, diff, hours = t
        clean_desc = desc.replace("'", "''")
        clean_name = name.replace("'", "''")
        val_lines.append(
            f"('{tid}', '{sid}', '{clean_name}', '{clean_desc}', {idx}, {sub_cnt}, '{diff}', {hours}, strftime('%s','now')*1000, strftime('%s','now')*1000)"
        )
    lines.append(",\n".join(val_lines) + ";\n")
    outfile.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(topics)} topics to {outfile.name}")


if __name__ == "__main__":
    generate_sql(EDEXCEL_IGCSE_TOPICS, OUT_IGCSE, "Syllabus topics for Pearson Edexcel IGCSE (14 subjects)")
    generate_sql(EDEXCEL_IAL_TOPICS, OUT_IAL, "Syllabus topics for Pearson Edexcel IAL (Modular Units)")
